/*
WhoisFreaks API

Testing DatabasesASNWHOISAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package whoisfreaks

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/WhoisFreaks/whoisfreaks-go"
)

func Test_whoisfreaks_DatabasesASNWHOISAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DatabasesASNWHOISAPIService DbAsnWhois", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DatabasesASNWHOISAPI.DbAsnWhois(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DatabasesASNWHOISAPIService DbAsnWhoisStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DatabasesASNWHOISAPI.DbAsnWhoisStatus(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
