/*
WhoisFreaks API

Testing DatabasesNewlyRegisteredAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package whoisfreaks

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/WhoisFreaks/whoisfreaks-go"
)

func Test_whoisfreaks_DatabasesNewlyRegisteredAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DatabasesNewlyRegisteredAPIService DbNewlyCctld", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DatabasesNewlyRegisteredAPI.DbNewlyCctld(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DatabasesNewlyRegisteredAPIService DbNewlyCctldCleaned", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DatabasesNewlyRegisteredAPI.DbNewlyCctldCleaned(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DatabasesNewlyRegisteredAPIService DbNewlyCctldJson", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DatabasesNewlyRegisteredAPI.DbNewlyCctldJson(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DatabasesNewlyRegisteredAPIService DbNewlyDns", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DatabasesNewlyRegisteredAPI.DbNewlyDns(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DatabasesNewlyRegisteredAPIService DbNewlyGtld", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DatabasesNewlyRegisteredAPI.DbNewlyGtld(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DatabasesNewlyRegisteredAPIService DbNewlyGtldCleaned", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DatabasesNewlyRegisteredAPI.DbNewlyGtldCleaned(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DatabasesNewlyRegisteredAPIService DbNewlyGtldJson", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DatabasesNewlyRegisteredAPI.DbNewlyGtldJson(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
