/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"os"
)


type DatabasesSubdomainsAPI interface {

	/*
	DbSubdomainsDaily Subdomains Daily

	Subdomains Daily. Returns the file/snapshot described by this operation.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return DatabasesSubdomainsAPIDbSubdomainsDailyRequest
	*/
	DbSubdomainsDaily(ctx context.Context) DatabasesSubdomainsAPIDbSubdomainsDailyRequest

	// DbSubdomainsDailyExecute executes the request
	//  @return *os.File
	DbSubdomainsDailyExecute(r DatabasesSubdomainsAPIDbSubdomainsDailyRequest) (*os.File, *http.Response, error)

	/*
	DbSubdomainsMonthly Subdomains Monthly

	Subdomains Monthly. Returns the file/snapshot described by this operation.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return DatabasesSubdomainsAPIDbSubdomainsMonthlyRequest
	*/
	DbSubdomainsMonthly(ctx context.Context) DatabasesSubdomainsAPIDbSubdomainsMonthlyRequest

	// DbSubdomainsMonthlyExecute executes the request
	//  @return *os.File
	DbSubdomainsMonthlyExecute(r DatabasesSubdomainsAPIDbSubdomainsMonthlyRequest) (*os.File, *http.Response, error)

	/*
	DbSubdomainsWeekly Subdomains Weekly

	Subdomains Weekly. Returns the file/snapshot described by this operation.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return DatabasesSubdomainsAPIDbSubdomainsWeeklyRequest
	*/
	DbSubdomainsWeekly(ctx context.Context) DatabasesSubdomainsAPIDbSubdomainsWeeklyRequest

	// DbSubdomainsWeeklyExecute executes the request
	//  @return *os.File
	DbSubdomainsWeeklyExecute(r DatabasesSubdomainsAPIDbSubdomainsWeeklyRequest) (*os.File, *http.Response, error)
}

// DatabasesSubdomainsAPIService DatabasesSubdomainsAPI service
type DatabasesSubdomainsAPIService service

type DatabasesSubdomainsAPIDbSubdomainsDailyRequest struct {
	ctx context.Context
	ApiService DatabasesSubdomainsAPI
	apiKey *string
	date *string
}

// Your WHOISFreaks API key
func (r DatabasesSubdomainsAPIDbSubdomainsDailyRequest) ApiKey(apiKey string) DatabasesSubdomainsAPIDbSubdomainsDailyRequest {
	r.apiKey = &apiKey
	return r
}

// yyyy-MM-dd; omit for latest
func (r DatabasesSubdomainsAPIDbSubdomainsDailyRequest) Date(date string) DatabasesSubdomainsAPIDbSubdomainsDailyRequest {
	r.date = &date
	return r
}

func (r DatabasesSubdomainsAPIDbSubdomainsDailyRequest) Execute() (*os.File, *http.Response, error) {
	return r.ApiService.DbSubdomainsDailyExecute(r)
}

/*
DbSubdomainsDaily Subdomains Daily

Subdomains Daily. Returns the file/snapshot described by this operation.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return DatabasesSubdomainsAPIDbSubdomainsDailyRequest
*/
func (a *DatabasesSubdomainsAPIService) DbSubdomainsDaily(ctx context.Context) DatabasesSubdomainsAPIDbSubdomainsDailyRequest {
	return DatabasesSubdomainsAPIDbSubdomainsDailyRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return *os.File
func (a *DatabasesSubdomainsAPIService) DbSubdomainsDailyExecute(r DatabasesSubdomainsAPIDbSubdomainsDailyRequest) (*os.File, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *os.File
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DatabasesSubdomainsAPIService.DbSubdomainsDaily")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v3.2/download/dbupdate/daily/subdomains"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.apiKey == nil {
		return localVarReturnValue, nil, reportError("apiKey is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "apiKey", r.apiKey, "form", "")
	if r.date != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "date", r.date, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/octet-stream", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("apiKey", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode >= 400 && localVarHTTPResponse.StatusCode < 500 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DatabasesSubdomainsAPIDbSubdomainsMonthlyRequest struct {
	ctx context.Context
	ApiService DatabasesSubdomainsAPI
	apiKey *string
	date *string
}

// Your WHOISFreaks API key
func (r DatabasesSubdomainsAPIDbSubdomainsMonthlyRequest) ApiKey(apiKey string) DatabasesSubdomainsAPIDbSubdomainsMonthlyRequest {
	r.apiKey = &apiKey
	return r
}

// yyyy-MM-dd; omit for latest
func (r DatabasesSubdomainsAPIDbSubdomainsMonthlyRequest) Date(date string) DatabasesSubdomainsAPIDbSubdomainsMonthlyRequest {
	r.date = &date
	return r
}

func (r DatabasesSubdomainsAPIDbSubdomainsMonthlyRequest) Execute() (*os.File, *http.Response, error) {
	return r.ApiService.DbSubdomainsMonthlyExecute(r)
}

/*
DbSubdomainsMonthly Subdomains Monthly

Subdomains Monthly. Returns the file/snapshot described by this operation.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return DatabasesSubdomainsAPIDbSubdomainsMonthlyRequest
*/
func (a *DatabasesSubdomainsAPIService) DbSubdomainsMonthly(ctx context.Context) DatabasesSubdomainsAPIDbSubdomainsMonthlyRequest {
	return DatabasesSubdomainsAPIDbSubdomainsMonthlyRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return *os.File
func (a *DatabasesSubdomainsAPIService) DbSubdomainsMonthlyExecute(r DatabasesSubdomainsAPIDbSubdomainsMonthlyRequest) (*os.File, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *os.File
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DatabasesSubdomainsAPIService.DbSubdomainsMonthly")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v3.2/download/dbupdate/monthly/subdomains"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.apiKey == nil {
		return localVarReturnValue, nil, reportError("apiKey is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "apiKey", r.apiKey, "form", "")
	if r.date != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "date", r.date, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/octet-stream", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("apiKey", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode >= 400 && localVarHTTPResponse.StatusCode < 500 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DatabasesSubdomainsAPIDbSubdomainsWeeklyRequest struct {
	ctx context.Context
	ApiService DatabasesSubdomainsAPI
	apiKey *string
	date *string
}

// Your WHOISFreaks API key
func (r DatabasesSubdomainsAPIDbSubdomainsWeeklyRequest) ApiKey(apiKey string) DatabasesSubdomainsAPIDbSubdomainsWeeklyRequest {
	r.apiKey = &apiKey
	return r
}

// yyyy-MM-dd; omit for latest
func (r DatabasesSubdomainsAPIDbSubdomainsWeeklyRequest) Date(date string) DatabasesSubdomainsAPIDbSubdomainsWeeklyRequest {
	r.date = &date
	return r
}

func (r DatabasesSubdomainsAPIDbSubdomainsWeeklyRequest) Execute() (*os.File, *http.Response, error) {
	return r.ApiService.DbSubdomainsWeeklyExecute(r)
}

/*
DbSubdomainsWeekly Subdomains Weekly

Subdomains Weekly. Returns the file/snapshot described by this operation.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return DatabasesSubdomainsAPIDbSubdomainsWeeklyRequest
*/
func (a *DatabasesSubdomainsAPIService) DbSubdomainsWeekly(ctx context.Context) DatabasesSubdomainsAPIDbSubdomainsWeeklyRequest {
	return DatabasesSubdomainsAPIDbSubdomainsWeeklyRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return *os.File
func (a *DatabasesSubdomainsAPIService) DbSubdomainsWeeklyExecute(r DatabasesSubdomainsAPIDbSubdomainsWeeklyRequest) (*os.File, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *os.File
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DatabasesSubdomainsAPIService.DbSubdomainsWeekly")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v3.2/download/dbupdate/weekly/subdomains"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.apiKey == nil {
		return localVarReturnValue, nil, reportError("apiKey is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "apiKey", r.apiKey, "form", "")
	if r.date != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "date", r.date, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/octet-stream", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("apiKey", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode >= 400 && localVarHTTPResponse.StatusCode < 500 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
