/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"os"
)


type DatabasesExpiringDroppedAPI interface {

	/*
	DbDropped Dropped Domains

	Dropped Domains. Returns the file/snapshot described by this operation.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return DatabasesExpiringDroppedAPIDbDroppedRequest
	*/
	DbDropped(ctx context.Context) DatabasesExpiringDroppedAPIDbDroppedRequest

	// DbDroppedExecute executes the request
	//  @return *os.File
	DbDroppedExecute(r DatabasesExpiringDroppedAPIDbDroppedRequest) (*os.File, *http.Response, error)

	/*
	DbDroppedBacklinks Dropped With Backlinks

	Dropped With Backlinks. Returns the file/snapshot described by this operation.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return DatabasesExpiringDroppedAPIDbDroppedBacklinksRequest
	*/
	DbDroppedBacklinks(ctx context.Context) DatabasesExpiringDroppedAPIDbDroppedBacklinksRequest

	// DbDroppedBacklinksExecute executes the request
	//  @return *os.File
	DbDroppedBacklinksExecute(r DatabasesExpiringDroppedAPIDbDroppedBacklinksRequest) (*os.File, *http.Response, error)

	/*
	DbDroppedJson Dropped Domains (JSON)

	Dropped Domains (JSON). Returns the file/snapshot described by this operation.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return DatabasesExpiringDroppedAPIDbDroppedJsonRequest
	*/
	DbDroppedJson(ctx context.Context) DatabasesExpiringDroppedAPIDbDroppedJsonRequest

	// DbDroppedJsonExecute executes the request
	//  @return []string
	DbDroppedJsonExecute(r DatabasesExpiringDroppedAPIDbDroppedJsonRequest) ([]string, *http.Response, error)

	/*
	DbExpired Expiring Domains

	Expiring Domains. Returns the file/snapshot described by this operation.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return DatabasesExpiringDroppedAPIDbExpiredRequest
	*/
	DbExpired(ctx context.Context) DatabasesExpiringDroppedAPIDbExpiredRequest

	// DbExpiredExecute executes the request
	//  @return *os.File
	DbExpiredExecute(r DatabasesExpiringDroppedAPIDbExpiredRequest) (*os.File, *http.Response, error)

	/*
	DbExpiredCleaned Expiring Cleaned WHOIS

	Expiring Cleaned WHOIS. Returns the file/snapshot described by this operation.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return DatabasesExpiringDroppedAPIDbExpiredCleanedRequest
	*/
	DbExpiredCleaned(ctx context.Context) DatabasesExpiringDroppedAPIDbExpiredCleanedRequest

	// DbExpiredCleanedExecute executes the request
	//  @return *os.File
	DbExpiredCleanedExecute(r DatabasesExpiringDroppedAPIDbExpiredCleanedRequest) (*os.File, *http.Response, error)
}

// DatabasesExpiringDroppedAPIService DatabasesExpiringDroppedAPI service
type DatabasesExpiringDroppedAPIService service

type DatabasesExpiringDroppedAPIDbDroppedRequest struct {
	ctx context.Context
	ApiService DatabasesExpiringDroppedAPI
	whois *bool
	date *string
}

func (r DatabasesExpiringDroppedAPIDbDroppedRequest) Whois(whois bool) DatabasesExpiringDroppedAPIDbDroppedRequest {
	r.whois = &whois
	return r
}

// yyyy-MM-dd; omit for latest
func (r DatabasesExpiringDroppedAPIDbDroppedRequest) Date(date string) DatabasesExpiringDroppedAPIDbDroppedRequest {
	r.date = &date
	return r
}

func (r DatabasesExpiringDroppedAPIDbDroppedRequest) Execute() (*os.File, *http.Response, error) {
	return r.ApiService.DbDroppedExecute(r)
}

/*
DbDropped Dropped Domains

Dropped Domains. Returns the file/snapshot described by this operation.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return DatabasesExpiringDroppedAPIDbDroppedRequest
*/
func (a *DatabasesExpiringDroppedAPIService) DbDropped(ctx context.Context) DatabasesExpiringDroppedAPIDbDroppedRequest {
	return DatabasesExpiringDroppedAPIDbDroppedRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return *os.File
func (a *DatabasesExpiringDroppedAPIService) DbDroppedExecute(r DatabasesExpiringDroppedAPIDbDroppedRequest) (*os.File, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *os.File
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DatabasesExpiringDroppedAPIService.DbDropped")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v3.1/download/domainer/dropped"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.whois == nil {
		return localVarReturnValue, nil, reportError("whois is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "whois", r.whois, "form", "")
	if r.date != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "date", r.date, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/octet-stream", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("apiKey", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode >= 400 && localVarHTTPResponse.StatusCode < 500 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DatabasesExpiringDroppedAPIDbDroppedBacklinksRequest struct {
	ctx context.Context
	ApiService DatabasesExpiringDroppedAPI
	whois *bool
	date *string
}

func (r DatabasesExpiringDroppedAPIDbDroppedBacklinksRequest) Whois(whois bool) DatabasesExpiringDroppedAPIDbDroppedBacklinksRequest {
	r.whois = &whois
	return r
}

// yyyy-MM-dd; omit for latest
func (r DatabasesExpiringDroppedAPIDbDroppedBacklinksRequest) Date(date string) DatabasesExpiringDroppedAPIDbDroppedBacklinksRequest {
	r.date = &date
	return r
}

func (r DatabasesExpiringDroppedAPIDbDroppedBacklinksRequest) Execute() (*os.File, *http.Response, error) {
	return r.ApiService.DbDroppedBacklinksExecute(r)
}

/*
DbDroppedBacklinks Dropped With Backlinks

Dropped With Backlinks. Returns the file/snapshot described by this operation.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return DatabasesExpiringDroppedAPIDbDroppedBacklinksRequest
*/
func (a *DatabasesExpiringDroppedAPIService) DbDroppedBacklinks(ctx context.Context) DatabasesExpiringDroppedAPIDbDroppedBacklinksRequest {
	return DatabasesExpiringDroppedAPIDbDroppedBacklinksRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return *os.File
func (a *DatabasesExpiringDroppedAPIService) DbDroppedBacklinksExecute(r DatabasesExpiringDroppedAPIDbDroppedBacklinksRequest) (*os.File, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *os.File
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DatabasesExpiringDroppedAPIService.DbDroppedBacklinks")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v3.3/download/domainer/dropped/backlinks"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.whois != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "whois", r.whois, "form", "")
	}
	if r.date != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "date", r.date, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/octet-stream", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("apiKey", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode >= 400 && localVarHTTPResponse.StatusCode < 500 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DatabasesExpiringDroppedAPIDbDroppedJsonRequest struct {
	ctx context.Context
	ApiService DatabasesExpiringDroppedAPI
	date *string
	tlds *string
}

// yyyy-MM-dd; omit for latest
func (r DatabasesExpiringDroppedAPIDbDroppedJsonRequest) Date(date string) DatabasesExpiringDroppedAPIDbDroppedJsonRequest {
	r.date = &date
	return r
}

func (r DatabasesExpiringDroppedAPIDbDroppedJsonRequest) Tlds(tlds string) DatabasesExpiringDroppedAPIDbDroppedJsonRequest {
	r.tlds = &tlds
	return r
}

func (r DatabasesExpiringDroppedAPIDbDroppedJsonRequest) Execute() ([]string, *http.Response, error) {
	return r.ApiService.DbDroppedJsonExecute(r)
}

/*
DbDroppedJson Dropped Domains (JSON)

Dropped Domains (JSON). Returns the file/snapshot described by this operation.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return DatabasesExpiringDroppedAPIDbDroppedJsonRequest
*/
func (a *DatabasesExpiringDroppedAPIService) DbDroppedJson(ctx context.Context) DatabasesExpiringDroppedAPIDbDroppedJsonRequest {
	return DatabasesExpiringDroppedAPIDbDroppedJsonRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []string
func (a *DatabasesExpiringDroppedAPIService) DbDroppedJsonExecute(r DatabasesExpiringDroppedAPIDbDroppedJsonRequest) ([]string, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []string
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DatabasesExpiringDroppedAPIService.DbDroppedJson")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v3.1/domains/dropped"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.date != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "date", r.date, "form", "")
	}
	if r.tlds != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "tlds", r.tlds, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("apiKey", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode >= 400 && localVarHTTPResponse.StatusCode < 500 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DatabasesExpiringDroppedAPIDbExpiredRequest struct {
	ctx context.Context
	ApiService DatabasesExpiringDroppedAPI
	whois *bool
	date *string
}

func (r DatabasesExpiringDroppedAPIDbExpiredRequest) Whois(whois bool) DatabasesExpiringDroppedAPIDbExpiredRequest {
	r.whois = &whois
	return r
}

// yyyy-MM-dd; omit for latest
func (r DatabasesExpiringDroppedAPIDbExpiredRequest) Date(date string) DatabasesExpiringDroppedAPIDbExpiredRequest {
	r.date = &date
	return r
}

func (r DatabasesExpiringDroppedAPIDbExpiredRequest) Execute() (*os.File, *http.Response, error) {
	return r.ApiService.DbExpiredExecute(r)
}

/*
DbExpired Expiring Domains

Expiring Domains. Returns the file/snapshot described by this operation.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return DatabasesExpiringDroppedAPIDbExpiredRequest
*/
func (a *DatabasesExpiringDroppedAPIService) DbExpired(ctx context.Context) DatabasesExpiringDroppedAPIDbExpiredRequest {
	return DatabasesExpiringDroppedAPIDbExpiredRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return *os.File
func (a *DatabasesExpiringDroppedAPIService) DbExpiredExecute(r DatabasesExpiringDroppedAPIDbExpiredRequest) (*os.File, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *os.File
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DatabasesExpiringDroppedAPIService.DbExpired")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v3.1/download/domainer/expired"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.whois == nil {
		return localVarReturnValue, nil, reportError("whois is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "whois", r.whois, "form", "")
	if r.date != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "date", r.date, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/octet-stream", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("apiKey", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode >= 400 && localVarHTTPResponse.StatusCode < 500 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DatabasesExpiringDroppedAPIDbExpiredCleanedRequest struct {
	ctx context.Context
	ApiService DatabasesExpiringDroppedAPI
	date *string
}

// yyyy-MM-dd; omit for latest
func (r DatabasesExpiringDroppedAPIDbExpiredCleanedRequest) Date(date string) DatabasesExpiringDroppedAPIDbExpiredCleanedRequest {
	r.date = &date
	return r
}

func (r DatabasesExpiringDroppedAPIDbExpiredCleanedRequest) Execute() (*os.File, *http.Response, error) {
	return r.ApiService.DbExpiredCleanedExecute(r)
}

/*
DbExpiredCleaned Expiring Cleaned WHOIS

Expiring Cleaned WHOIS. Returns the file/snapshot described by this operation.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return DatabasesExpiringDroppedAPIDbExpiredCleanedRequest
*/
func (a *DatabasesExpiringDroppedAPIService) DbExpiredCleaned(ctx context.Context) DatabasesExpiringDroppedAPIDbExpiredCleanedRequest {
	return DatabasesExpiringDroppedAPIDbExpiredCleanedRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return *os.File
func (a *DatabasesExpiringDroppedAPIService) DbExpiredCleanedExecute(r DatabasesExpiringDroppedAPIDbExpiredCleanedRequest) (*os.File, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *os.File
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DatabasesExpiringDroppedAPIService.DbExpiredCleaned")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v3.1/download/domainer/expired/cleaned"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.date != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "date", r.date, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/octet-stream", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("apiKey", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode >= 400 && localVarHTTPResponse.StatusCode < 500 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
