/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"os"
)


type DatabasesThreatFeedAPI interface {

	/*
	DownloadThreatFeedMalware Download the daily malware threat feed (CSV)

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return DatabasesThreatFeedAPIDownloadThreatFeedMalwareRequest
	*/
	DownloadThreatFeedMalware(ctx context.Context) DatabasesThreatFeedAPIDownloadThreatFeedMalwareRequest

	// DownloadThreatFeedMalwareExecute executes the request
	//  @return *os.File
	DownloadThreatFeedMalwareExecute(r DatabasesThreatFeedAPIDownloadThreatFeedMalwareRequest) (*os.File, *http.Response, error)

	/*
	DownloadThreatFeedMalwareSample Download a sample of the malware threat feed (CSV)

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return DatabasesThreatFeedAPIDownloadThreatFeedMalwareSampleRequest
	*/
	DownloadThreatFeedMalwareSample(ctx context.Context) DatabasesThreatFeedAPIDownloadThreatFeedMalwareSampleRequest

	// DownloadThreatFeedMalwareSampleExecute executes the request
	//  @return *os.File
	DownloadThreatFeedMalwareSampleExecute(r DatabasesThreatFeedAPIDownloadThreatFeedMalwareSampleRequest) (*os.File, *http.Response, error)

	/*
	DownloadThreatFeedPhishing Download the daily phishing threat feed (CSV)

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return DatabasesThreatFeedAPIDownloadThreatFeedPhishingRequest
	*/
	DownloadThreatFeedPhishing(ctx context.Context) DatabasesThreatFeedAPIDownloadThreatFeedPhishingRequest

	// DownloadThreatFeedPhishingExecute executes the request
	//  @return *os.File
	DownloadThreatFeedPhishingExecute(r DatabasesThreatFeedAPIDownloadThreatFeedPhishingRequest) (*os.File, *http.Response, error)

	/*
	DownloadThreatFeedPhishingSample Download a sample of the phishing threat feed (CSV)

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return DatabasesThreatFeedAPIDownloadThreatFeedPhishingSampleRequest
	*/
	DownloadThreatFeedPhishingSample(ctx context.Context) DatabasesThreatFeedAPIDownloadThreatFeedPhishingSampleRequest

	// DownloadThreatFeedPhishingSampleExecute executes the request
	//  @return *os.File
	DownloadThreatFeedPhishingSampleExecute(r DatabasesThreatFeedAPIDownloadThreatFeedPhishingSampleRequest) (*os.File, *http.Response, error)

	/*
	DownloadThreatFeedSpam Download the daily spam threat feed (CSV)

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return DatabasesThreatFeedAPIDownloadThreatFeedSpamRequest
	*/
	DownloadThreatFeedSpam(ctx context.Context) DatabasesThreatFeedAPIDownloadThreatFeedSpamRequest

	// DownloadThreatFeedSpamExecute executes the request
	//  @return *os.File
	DownloadThreatFeedSpamExecute(r DatabasesThreatFeedAPIDownloadThreatFeedSpamRequest) (*os.File, *http.Response, error)

	/*
	DownloadThreatFeedSpamSample Download a sample of the spam threat feed (CSV)

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return DatabasesThreatFeedAPIDownloadThreatFeedSpamSampleRequest
	*/
	DownloadThreatFeedSpamSample(ctx context.Context) DatabasesThreatFeedAPIDownloadThreatFeedSpamSampleRequest

	// DownloadThreatFeedSpamSampleExecute executes the request
	//  @return *os.File
	DownloadThreatFeedSpamSampleExecute(r DatabasesThreatFeedAPIDownloadThreatFeedSpamSampleRequest) (*os.File, *http.Response, error)
}

// DatabasesThreatFeedAPIService DatabasesThreatFeedAPI service
type DatabasesThreatFeedAPIService service

type DatabasesThreatFeedAPIDownloadThreatFeedMalwareRequest struct {
	ctx context.Context
	ApiService DatabasesThreatFeedAPI
	date *string
}

// Feed date (yyyy-MM-dd); defaults to latest available
func (r DatabasesThreatFeedAPIDownloadThreatFeedMalwareRequest) Date(date string) DatabasesThreatFeedAPIDownloadThreatFeedMalwareRequest {
	r.date = &date
	return r
}

func (r DatabasesThreatFeedAPIDownloadThreatFeedMalwareRequest) Execute() (*os.File, *http.Response, error) {
	return r.ApiService.DownloadThreatFeedMalwareExecute(r)
}

/*
DownloadThreatFeedMalware Download the daily malware threat feed (CSV)

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return DatabasesThreatFeedAPIDownloadThreatFeedMalwareRequest
*/
func (a *DatabasesThreatFeedAPIService) DownloadThreatFeedMalware(ctx context.Context) DatabasesThreatFeedAPIDownloadThreatFeedMalwareRequest {
	return DatabasesThreatFeedAPIDownloadThreatFeedMalwareRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return *os.File
func (a *DatabasesThreatFeedAPIService) DownloadThreatFeedMalwareExecute(r DatabasesThreatFeedAPIDownloadThreatFeedMalwareRequest) (*os.File, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *os.File
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DatabasesThreatFeedAPIService.DownloadThreatFeedMalware")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v3.4/download/threat-feed/malware"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.date != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "date", r.date, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/octet-stream"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("apiKey", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DatabasesThreatFeedAPIDownloadThreatFeedMalwareSampleRequest struct {
	ctx context.Context
	ApiService DatabasesThreatFeedAPI
}

func (r DatabasesThreatFeedAPIDownloadThreatFeedMalwareSampleRequest) Execute() (*os.File, *http.Response, error) {
	return r.ApiService.DownloadThreatFeedMalwareSampleExecute(r)
}

/*
DownloadThreatFeedMalwareSample Download a sample of the malware threat feed (CSV)

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return DatabasesThreatFeedAPIDownloadThreatFeedMalwareSampleRequest
*/
func (a *DatabasesThreatFeedAPIService) DownloadThreatFeedMalwareSample(ctx context.Context) DatabasesThreatFeedAPIDownloadThreatFeedMalwareSampleRequest {
	return DatabasesThreatFeedAPIDownloadThreatFeedMalwareSampleRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return *os.File
func (a *DatabasesThreatFeedAPIService) DownloadThreatFeedMalwareSampleExecute(r DatabasesThreatFeedAPIDownloadThreatFeedMalwareSampleRequest) (*os.File, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *os.File
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DatabasesThreatFeedAPIService.DownloadThreatFeedMalwareSample")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v3.4/download/threat-feed/malware/sample"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/octet-stream"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("apiKey", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DatabasesThreatFeedAPIDownloadThreatFeedPhishingRequest struct {
	ctx context.Context
	ApiService DatabasesThreatFeedAPI
	date *string
}

// Feed date (yyyy-MM-dd); defaults to latest available
func (r DatabasesThreatFeedAPIDownloadThreatFeedPhishingRequest) Date(date string) DatabasesThreatFeedAPIDownloadThreatFeedPhishingRequest {
	r.date = &date
	return r
}

func (r DatabasesThreatFeedAPIDownloadThreatFeedPhishingRequest) Execute() (*os.File, *http.Response, error) {
	return r.ApiService.DownloadThreatFeedPhishingExecute(r)
}

/*
DownloadThreatFeedPhishing Download the daily phishing threat feed (CSV)

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return DatabasesThreatFeedAPIDownloadThreatFeedPhishingRequest
*/
func (a *DatabasesThreatFeedAPIService) DownloadThreatFeedPhishing(ctx context.Context) DatabasesThreatFeedAPIDownloadThreatFeedPhishingRequest {
	return DatabasesThreatFeedAPIDownloadThreatFeedPhishingRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return *os.File
func (a *DatabasesThreatFeedAPIService) DownloadThreatFeedPhishingExecute(r DatabasesThreatFeedAPIDownloadThreatFeedPhishingRequest) (*os.File, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *os.File
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DatabasesThreatFeedAPIService.DownloadThreatFeedPhishing")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v3.4/download/threat-feed/phishing"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.date != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "date", r.date, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/octet-stream"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("apiKey", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DatabasesThreatFeedAPIDownloadThreatFeedPhishingSampleRequest struct {
	ctx context.Context
	ApiService DatabasesThreatFeedAPI
}

func (r DatabasesThreatFeedAPIDownloadThreatFeedPhishingSampleRequest) Execute() (*os.File, *http.Response, error) {
	return r.ApiService.DownloadThreatFeedPhishingSampleExecute(r)
}

/*
DownloadThreatFeedPhishingSample Download a sample of the phishing threat feed (CSV)

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return DatabasesThreatFeedAPIDownloadThreatFeedPhishingSampleRequest
*/
func (a *DatabasesThreatFeedAPIService) DownloadThreatFeedPhishingSample(ctx context.Context) DatabasesThreatFeedAPIDownloadThreatFeedPhishingSampleRequest {
	return DatabasesThreatFeedAPIDownloadThreatFeedPhishingSampleRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return *os.File
func (a *DatabasesThreatFeedAPIService) DownloadThreatFeedPhishingSampleExecute(r DatabasesThreatFeedAPIDownloadThreatFeedPhishingSampleRequest) (*os.File, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *os.File
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DatabasesThreatFeedAPIService.DownloadThreatFeedPhishingSample")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v3.4/download/threat-feed/phishing/sample"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/octet-stream"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("apiKey", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DatabasesThreatFeedAPIDownloadThreatFeedSpamRequest struct {
	ctx context.Context
	ApiService DatabasesThreatFeedAPI
	date *string
}

// Feed date (yyyy-MM-dd); defaults to latest available
func (r DatabasesThreatFeedAPIDownloadThreatFeedSpamRequest) Date(date string) DatabasesThreatFeedAPIDownloadThreatFeedSpamRequest {
	r.date = &date
	return r
}

func (r DatabasesThreatFeedAPIDownloadThreatFeedSpamRequest) Execute() (*os.File, *http.Response, error) {
	return r.ApiService.DownloadThreatFeedSpamExecute(r)
}

/*
DownloadThreatFeedSpam Download the daily spam threat feed (CSV)

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return DatabasesThreatFeedAPIDownloadThreatFeedSpamRequest
*/
func (a *DatabasesThreatFeedAPIService) DownloadThreatFeedSpam(ctx context.Context) DatabasesThreatFeedAPIDownloadThreatFeedSpamRequest {
	return DatabasesThreatFeedAPIDownloadThreatFeedSpamRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return *os.File
func (a *DatabasesThreatFeedAPIService) DownloadThreatFeedSpamExecute(r DatabasesThreatFeedAPIDownloadThreatFeedSpamRequest) (*os.File, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *os.File
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DatabasesThreatFeedAPIService.DownloadThreatFeedSpam")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v3.4/download/threat-feed/spam"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.date != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "date", r.date, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/octet-stream"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("apiKey", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DatabasesThreatFeedAPIDownloadThreatFeedSpamSampleRequest struct {
	ctx context.Context
	ApiService DatabasesThreatFeedAPI
}

func (r DatabasesThreatFeedAPIDownloadThreatFeedSpamSampleRequest) Execute() (*os.File, *http.Response, error) {
	return r.ApiService.DownloadThreatFeedSpamSampleExecute(r)
}

/*
DownloadThreatFeedSpamSample Download a sample of the spam threat feed (CSV)

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return DatabasesThreatFeedAPIDownloadThreatFeedSpamSampleRequest
*/
func (a *DatabasesThreatFeedAPIService) DownloadThreatFeedSpamSample(ctx context.Context) DatabasesThreatFeedAPIDownloadThreatFeedSpamSampleRequest {
	return DatabasesThreatFeedAPIDownloadThreatFeedSpamSampleRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return *os.File
func (a *DatabasesThreatFeedAPIService) DownloadThreatFeedSpamSampleExecute(r DatabasesThreatFeedAPIDownloadThreatFeedSpamSampleRequest) (*os.File, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *os.File
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DatabasesThreatFeedAPIService.DownloadThreatFeedSpamSample")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v3.4/download/threat-feed/spam/sample"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/octet-stream"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("apiKey", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
