/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"encoding/json"
)

// checks if the WhoisHistoricalResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WhoisHistoricalResponse{}

// WhoisHistoricalResponse struct for WhoisHistoricalResponse
type WhoisHistoricalResponse struct {
	Status *bool `json:"status,omitempty"`
	Whois *string `json:"whois,omitempty"`
	TotalRecords *string `json:"total_records,omitempty"`
	WhoisDomainsHistorical []WhoisHistoricalItem `json:"whois_domains_historical,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WhoisHistoricalResponse WhoisHistoricalResponse

// NewWhoisHistoricalResponse instantiates a new WhoisHistoricalResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhoisHistoricalResponse() *WhoisHistoricalResponse {
	this := WhoisHistoricalResponse{}
	return &this
}

// NewWhoisHistoricalResponseWithDefaults instantiates a new WhoisHistoricalResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhoisHistoricalResponseWithDefaults() *WhoisHistoricalResponse {
	this := WhoisHistoricalResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *WhoisHistoricalResponse) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoisHistoricalResponse) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *WhoisHistoricalResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *WhoisHistoricalResponse) SetStatus(v bool) {
	o.Status = &v
}

// GetWhois returns the Whois field value if set, zero value otherwise.
func (o *WhoisHistoricalResponse) GetWhois() string {
	if o == nil || IsNil(o.Whois) {
		var ret string
		return ret
	}
	return *o.Whois
}

// GetWhoisOk returns a tuple with the Whois field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoisHistoricalResponse) GetWhoisOk() (*string, bool) {
	if o == nil || IsNil(o.Whois) {
		return nil, false
	}
	return o.Whois, true
}

// HasWhois returns a boolean if a field has been set.
func (o *WhoisHistoricalResponse) HasWhois() bool {
	if o != nil && !IsNil(o.Whois) {
		return true
	}

	return false
}

// SetWhois gets a reference to the given string and assigns it to the Whois field.
func (o *WhoisHistoricalResponse) SetWhois(v string) {
	o.Whois = &v
}

// GetTotalRecords returns the TotalRecords field value if set, zero value otherwise.
func (o *WhoisHistoricalResponse) GetTotalRecords() string {
	if o == nil || IsNil(o.TotalRecords) {
		var ret string
		return ret
	}
	return *o.TotalRecords
}

// GetTotalRecordsOk returns a tuple with the TotalRecords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoisHistoricalResponse) GetTotalRecordsOk() (*string, bool) {
	if o == nil || IsNil(o.TotalRecords) {
		return nil, false
	}
	return o.TotalRecords, true
}

// HasTotalRecords returns a boolean if a field has been set.
func (o *WhoisHistoricalResponse) HasTotalRecords() bool {
	if o != nil && !IsNil(o.TotalRecords) {
		return true
	}

	return false
}

// SetTotalRecords gets a reference to the given string and assigns it to the TotalRecords field.
func (o *WhoisHistoricalResponse) SetTotalRecords(v string) {
	o.TotalRecords = &v
}

// GetWhoisDomainsHistorical returns the WhoisDomainsHistorical field value if set, zero value otherwise.
func (o *WhoisHistoricalResponse) GetWhoisDomainsHistorical() []WhoisHistoricalItem {
	if o == nil || IsNil(o.WhoisDomainsHistorical) {
		var ret []WhoisHistoricalItem
		return ret
	}
	return o.WhoisDomainsHistorical
}

// GetWhoisDomainsHistoricalOk returns a tuple with the WhoisDomainsHistorical field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoisHistoricalResponse) GetWhoisDomainsHistoricalOk() ([]WhoisHistoricalItem, bool) {
	if o == nil || IsNil(o.WhoisDomainsHistorical) {
		return nil, false
	}
	return o.WhoisDomainsHistorical, true
}

// HasWhoisDomainsHistorical returns a boolean if a field has been set.
func (o *WhoisHistoricalResponse) HasWhoisDomainsHistorical() bool {
	if o != nil && !IsNil(o.WhoisDomainsHistorical) {
		return true
	}

	return false
}

// SetWhoisDomainsHistorical gets a reference to the given []WhoisHistoricalItem and assigns it to the WhoisDomainsHistorical field.
func (o *WhoisHistoricalResponse) SetWhoisDomainsHistorical(v []WhoisHistoricalItem) {
	o.WhoisDomainsHistorical = v
}

func (o WhoisHistoricalResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WhoisHistoricalResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Whois) {
		toSerialize["whois"] = o.Whois
	}
	if !IsNil(o.TotalRecords) {
		toSerialize["total_records"] = o.TotalRecords
	}
	if !IsNil(o.WhoisDomainsHistorical) {
		toSerialize["whois_domains_historical"] = o.WhoisDomainsHistorical
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WhoisHistoricalResponse) UnmarshalJSON(data []byte) (err error) {
	varWhoisHistoricalResponse := _WhoisHistoricalResponse{}

	err = json.Unmarshal(data, &varWhoisHistoricalResponse)

	if err != nil {
		return err
	}

	*o = WhoisHistoricalResponse(varWhoisHistoricalResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "whois")
		delete(additionalProperties, "total_records")
		delete(additionalProperties, "whois_domains_historical")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWhoisHistoricalResponse struct {
	value *WhoisHistoricalResponse
	isSet bool
}

func (v NullableWhoisHistoricalResponse) Get() *WhoisHistoricalResponse {
	return v.value
}

func (v *NullableWhoisHistoricalResponse) Set(val *WhoisHistoricalResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWhoisHistoricalResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWhoisHistoricalResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhoisHistoricalResponse(val *WhoisHistoricalResponse) *NullableWhoisHistoricalResponse {
	return &NullableWhoisHistoricalResponse{value: val, isSet: true}
}

func (v NullableWhoisHistoricalResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhoisHistoricalResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


