/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"encoding/json"
)

// checks if the DatabaseUpdates type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DatabaseUpdates{}

// DatabaseUpdates struct for DatabaseUpdates
type DatabaseUpdates struct {
	DomainWhois *UpdateFrequencies `json:"domain_whois,omitempty"`
	Dns *UpdateFrequencies `json:"dns,omitempty"`
	Subdomains *UpdateFrequencies `json:"subdomains,omitempty"`
	IpWhois *UpdateFrequencies `json:"ip_whois,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DatabaseUpdates DatabaseUpdates

// NewDatabaseUpdates instantiates a new DatabaseUpdates object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDatabaseUpdates() *DatabaseUpdates {
	this := DatabaseUpdates{}
	return &this
}

// NewDatabaseUpdatesWithDefaults instantiates a new DatabaseUpdates object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDatabaseUpdatesWithDefaults() *DatabaseUpdates {
	this := DatabaseUpdates{}
	return &this
}

// GetDomainWhois returns the DomainWhois field value if set, zero value otherwise.
func (o *DatabaseUpdates) GetDomainWhois() UpdateFrequencies {
	if o == nil || IsNil(o.DomainWhois) {
		var ret UpdateFrequencies
		return ret
	}
	return *o.DomainWhois
}

// GetDomainWhoisOk returns a tuple with the DomainWhois field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabaseUpdates) GetDomainWhoisOk() (*UpdateFrequencies, bool) {
	if o == nil || IsNil(o.DomainWhois) {
		return nil, false
	}
	return o.DomainWhois, true
}

// HasDomainWhois returns a boolean if a field has been set.
func (o *DatabaseUpdates) HasDomainWhois() bool {
	if o != nil && !IsNil(o.DomainWhois) {
		return true
	}

	return false
}

// SetDomainWhois gets a reference to the given UpdateFrequencies and assigns it to the DomainWhois field.
func (o *DatabaseUpdates) SetDomainWhois(v UpdateFrequencies) {
	o.DomainWhois = &v
}

// GetDns returns the Dns field value if set, zero value otherwise.
func (o *DatabaseUpdates) GetDns() UpdateFrequencies {
	if o == nil || IsNil(o.Dns) {
		var ret UpdateFrequencies
		return ret
	}
	return *o.Dns
}

// GetDnsOk returns a tuple with the Dns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabaseUpdates) GetDnsOk() (*UpdateFrequencies, bool) {
	if o == nil || IsNil(o.Dns) {
		return nil, false
	}
	return o.Dns, true
}

// HasDns returns a boolean if a field has been set.
func (o *DatabaseUpdates) HasDns() bool {
	if o != nil && !IsNil(o.Dns) {
		return true
	}

	return false
}

// SetDns gets a reference to the given UpdateFrequencies and assigns it to the Dns field.
func (o *DatabaseUpdates) SetDns(v UpdateFrequencies) {
	o.Dns = &v
}

// GetSubdomains returns the Subdomains field value if set, zero value otherwise.
func (o *DatabaseUpdates) GetSubdomains() UpdateFrequencies {
	if o == nil || IsNil(o.Subdomains) {
		var ret UpdateFrequencies
		return ret
	}
	return *o.Subdomains
}

// GetSubdomainsOk returns a tuple with the Subdomains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabaseUpdates) GetSubdomainsOk() (*UpdateFrequencies, bool) {
	if o == nil || IsNil(o.Subdomains) {
		return nil, false
	}
	return o.Subdomains, true
}

// HasSubdomains returns a boolean if a field has been set.
func (o *DatabaseUpdates) HasSubdomains() bool {
	if o != nil && !IsNil(o.Subdomains) {
		return true
	}

	return false
}

// SetSubdomains gets a reference to the given UpdateFrequencies and assigns it to the Subdomains field.
func (o *DatabaseUpdates) SetSubdomains(v UpdateFrequencies) {
	o.Subdomains = &v
}

// GetIpWhois returns the IpWhois field value if set, zero value otherwise.
func (o *DatabaseUpdates) GetIpWhois() UpdateFrequencies {
	if o == nil || IsNil(o.IpWhois) {
		var ret UpdateFrequencies
		return ret
	}
	return *o.IpWhois
}

// GetIpWhoisOk returns a tuple with the IpWhois field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabaseUpdates) GetIpWhoisOk() (*UpdateFrequencies, bool) {
	if o == nil || IsNil(o.IpWhois) {
		return nil, false
	}
	return o.IpWhois, true
}

// HasIpWhois returns a boolean if a field has been set.
func (o *DatabaseUpdates) HasIpWhois() bool {
	if o != nil && !IsNil(o.IpWhois) {
		return true
	}

	return false
}

// SetIpWhois gets a reference to the given UpdateFrequencies and assigns it to the IpWhois field.
func (o *DatabaseUpdates) SetIpWhois(v UpdateFrequencies) {
	o.IpWhois = &v
}

func (o DatabaseUpdates) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DatabaseUpdates) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DomainWhois) {
		toSerialize["domain_whois"] = o.DomainWhois
	}
	if !IsNil(o.Dns) {
		toSerialize["dns"] = o.Dns
	}
	if !IsNil(o.Subdomains) {
		toSerialize["subdomains"] = o.Subdomains
	}
	if !IsNil(o.IpWhois) {
		toSerialize["ip_whois"] = o.IpWhois
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DatabaseUpdates) UnmarshalJSON(data []byte) (err error) {
	varDatabaseUpdates := _DatabaseUpdates{}

	err = json.Unmarshal(data, &varDatabaseUpdates)

	if err != nil {
		return err
	}

	*o = DatabaseUpdates(varDatabaseUpdates)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "domain_whois")
		delete(additionalProperties, "dns")
		delete(additionalProperties, "subdomains")
		delete(additionalProperties, "ip_whois")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDatabaseUpdates struct {
	value *DatabaseUpdates
	isSet bool
}

func (v NullableDatabaseUpdates) Get() *DatabaseUpdates {
	return v.value
}

func (v *NullableDatabaseUpdates) Set(val *DatabaseUpdates) {
	v.value = val
	v.isSet = true
}

func (v NullableDatabaseUpdates) IsSet() bool {
	return v.isSet
}

func (v *NullableDatabaseUpdates) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDatabaseUpdates(val *DatabaseUpdates) *NullableDatabaseUpdates {
	return &NullableDatabaseUpdates{value: val, isSet: true}
}

func (v NullableDatabaseUpdates) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDatabaseUpdates) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


