/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"encoding/json"
)

// checks if the PersonalInformation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PersonalInformation{}

// PersonalInformation Contact block (registrant/administrative/technical/billing).
type PersonalInformation struct {
	Id *string `json:"id,omitempty"`
	IdType *string `json:"id_type,omitempty"`
	Handle *string `json:"handle,omitempty"`
	Name *string `json:"name,omitempty"`
	Company *string `json:"company,omitempty"`
	Street *string `json:"street,omitempty"`
	City *string `json:"city,omitempty"`
	State *string `json:"state,omitempty"`
	ZipCode *string `json:"zip_code,omitempty"`
	CountryName *string `json:"country_name,omitempty"`
	CountryCode *string `json:"country_code,omitempty"`
	EmailAddress *string `json:"email_address,omitempty"`
	Phone *string `json:"phone,omitempty"`
	Fax *string `json:"fax,omitempty"`
	MailingAddress *string `json:"mailing_address,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PersonalInformation PersonalInformation

// NewPersonalInformation instantiates a new PersonalInformation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPersonalInformation() *PersonalInformation {
	this := PersonalInformation{}
	return &this
}

// NewPersonalInformationWithDefaults instantiates a new PersonalInformation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPersonalInformationWithDefaults() *PersonalInformation {
	this := PersonalInformation{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PersonalInformation) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonalInformation) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PersonalInformation) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PersonalInformation) SetId(v string) {
	o.Id = &v
}

// GetIdType returns the IdType field value if set, zero value otherwise.
func (o *PersonalInformation) GetIdType() string {
	if o == nil || IsNil(o.IdType) {
		var ret string
		return ret
	}
	return *o.IdType
}

// GetIdTypeOk returns a tuple with the IdType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonalInformation) GetIdTypeOk() (*string, bool) {
	if o == nil || IsNil(o.IdType) {
		return nil, false
	}
	return o.IdType, true
}

// HasIdType returns a boolean if a field has been set.
func (o *PersonalInformation) HasIdType() bool {
	if o != nil && !IsNil(o.IdType) {
		return true
	}

	return false
}

// SetIdType gets a reference to the given string and assigns it to the IdType field.
func (o *PersonalInformation) SetIdType(v string) {
	o.IdType = &v
}

// GetHandle returns the Handle field value if set, zero value otherwise.
func (o *PersonalInformation) GetHandle() string {
	if o == nil || IsNil(o.Handle) {
		var ret string
		return ret
	}
	return *o.Handle
}

// GetHandleOk returns a tuple with the Handle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonalInformation) GetHandleOk() (*string, bool) {
	if o == nil || IsNil(o.Handle) {
		return nil, false
	}
	return o.Handle, true
}

// HasHandle returns a boolean if a field has been set.
func (o *PersonalInformation) HasHandle() bool {
	if o != nil && !IsNil(o.Handle) {
		return true
	}

	return false
}

// SetHandle gets a reference to the given string and assigns it to the Handle field.
func (o *PersonalInformation) SetHandle(v string) {
	o.Handle = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PersonalInformation) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonalInformation) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PersonalInformation) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PersonalInformation) SetName(v string) {
	o.Name = &v
}

// GetCompany returns the Company field value if set, zero value otherwise.
func (o *PersonalInformation) GetCompany() string {
	if o == nil || IsNil(o.Company) {
		var ret string
		return ret
	}
	return *o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonalInformation) GetCompanyOk() (*string, bool) {
	if o == nil || IsNil(o.Company) {
		return nil, false
	}
	return o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *PersonalInformation) HasCompany() bool {
	if o != nil && !IsNil(o.Company) {
		return true
	}

	return false
}

// SetCompany gets a reference to the given string and assigns it to the Company field.
func (o *PersonalInformation) SetCompany(v string) {
	o.Company = &v
}

// GetStreet returns the Street field value if set, zero value otherwise.
func (o *PersonalInformation) GetStreet() string {
	if o == nil || IsNil(o.Street) {
		var ret string
		return ret
	}
	return *o.Street
}

// GetStreetOk returns a tuple with the Street field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonalInformation) GetStreetOk() (*string, bool) {
	if o == nil || IsNil(o.Street) {
		return nil, false
	}
	return o.Street, true
}

// HasStreet returns a boolean if a field has been set.
func (o *PersonalInformation) HasStreet() bool {
	if o != nil && !IsNil(o.Street) {
		return true
	}

	return false
}

// SetStreet gets a reference to the given string and assigns it to the Street field.
func (o *PersonalInformation) SetStreet(v string) {
	o.Street = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *PersonalInformation) GetCity() string {
	if o == nil || IsNil(o.City) {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonalInformation) GetCityOk() (*string, bool) {
	if o == nil || IsNil(o.City) {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *PersonalInformation) HasCity() bool {
	if o != nil && !IsNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *PersonalInformation) SetCity(v string) {
	o.City = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *PersonalInformation) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonalInformation) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *PersonalInformation) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *PersonalInformation) SetState(v string) {
	o.State = &v
}

// GetZipCode returns the ZipCode field value if set, zero value otherwise.
func (o *PersonalInformation) GetZipCode() string {
	if o == nil || IsNil(o.ZipCode) {
		var ret string
		return ret
	}
	return *o.ZipCode
}

// GetZipCodeOk returns a tuple with the ZipCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonalInformation) GetZipCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ZipCode) {
		return nil, false
	}
	return o.ZipCode, true
}

// HasZipCode returns a boolean if a field has been set.
func (o *PersonalInformation) HasZipCode() bool {
	if o != nil && !IsNil(o.ZipCode) {
		return true
	}

	return false
}

// SetZipCode gets a reference to the given string and assigns it to the ZipCode field.
func (o *PersonalInformation) SetZipCode(v string) {
	o.ZipCode = &v
}

// GetCountryName returns the CountryName field value if set, zero value otherwise.
func (o *PersonalInformation) GetCountryName() string {
	if o == nil || IsNil(o.CountryName) {
		var ret string
		return ret
	}
	return *o.CountryName
}

// GetCountryNameOk returns a tuple with the CountryName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonalInformation) GetCountryNameOk() (*string, bool) {
	if o == nil || IsNil(o.CountryName) {
		return nil, false
	}
	return o.CountryName, true
}

// HasCountryName returns a boolean if a field has been set.
func (o *PersonalInformation) HasCountryName() bool {
	if o != nil && !IsNil(o.CountryName) {
		return true
	}

	return false
}

// SetCountryName gets a reference to the given string and assigns it to the CountryName field.
func (o *PersonalInformation) SetCountryName(v string) {
	o.CountryName = &v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *PersonalInformation) GetCountryCode() string {
	if o == nil || IsNil(o.CountryCode) {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonalInformation) GetCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CountryCode) {
		return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *PersonalInformation) HasCountryCode() bool {
	if o != nil && !IsNil(o.CountryCode) {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *PersonalInformation) SetCountryCode(v string) {
	o.CountryCode = &v
}

// GetEmailAddress returns the EmailAddress field value if set, zero value otherwise.
func (o *PersonalInformation) GetEmailAddress() string {
	if o == nil || IsNil(o.EmailAddress) {
		var ret string
		return ret
	}
	return *o.EmailAddress
}

// GetEmailAddressOk returns a tuple with the EmailAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonalInformation) GetEmailAddressOk() (*string, bool) {
	if o == nil || IsNil(o.EmailAddress) {
		return nil, false
	}
	return o.EmailAddress, true
}

// HasEmailAddress returns a boolean if a field has been set.
func (o *PersonalInformation) HasEmailAddress() bool {
	if o != nil && !IsNil(o.EmailAddress) {
		return true
	}

	return false
}

// SetEmailAddress gets a reference to the given string and assigns it to the EmailAddress field.
func (o *PersonalInformation) SetEmailAddress(v string) {
	o.EmailAddress = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *PersonalInformation) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonalInformation) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *PersonalInformation) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *PersonalInformation) SetPhone(v string) {
	o.Phone = &v
}

// GetFax returns the Fax field value if set, zero value otherwise.
func (o *PersonalInformation) GetFax() string {
	if o == nil || IsNil(o.Fax) {
		var ret string
		return ret
	}
	return *o.Fax
}

// GetFaxOk returns a tuple with the Fax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonalInformation) GetFaxOk() (*string, bool) {
	if o == nil || IsNil(o.Fax) {
		return nil, false
	}
	return o.Fax, true
}

// HasFax returns a boolean if a field has been set.
func (o *PersonalInformation) HasFax() bool {
	if o != nil && !IsNil(o.Fax) {
		return true
	}

	return false
}

// SetFax gets a reference to the given string and assigns it to the Fax field.
func (o *PersonalInformation) SetFax(v string) {
	o.Fax = &v
}

// GetMailingAddress returns the MailingAddress field value if set, zero value otherwise.
func (o *PersonalInformation) GetMailingAddress() string {
	if o == nil || IsNil(o.MailingAddress) {
		var ret string
		return ret
	}
	return *o.MailingAddress
}

// GetMailingAddressOk returns a tuple with the MailingAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonalInformation) GetMailingAddressOk() (*string, bool) {
	if o == nil || IsNil(o.MailingAddress) {
		return nil, false
	}
	return o.MailingAddress, true
}

// HasMailingAddress returns a boolean if a field has been set.
func (o *PersonalInformation) HasMailingAddress() bool {
	if o != nil && !IsNil(o.MailingAddress) {
		return true
	}

	return false
}

// SetMailingAddress gets a reference to the given string and assigns it to the MailingAddress field.
func (o *PersonalInformation) SetMailingAddress(v string) {
	o.MailingAddress = &v
}

func (o PersonalInformation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PersonalInformation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IdType) {
		toSerialize["id_type"] = o.IdType
	}
	if !IsNil(o.Handle) {
		toSerialize["handle"] = o.Handle
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Company) {
		toSerialize["company"] = o.Company
	}
	if !IsNil(o.Street) {
		toSerialize["street"] = o.Street
	}
	if !IsNil(o.City) {
		toSerialize["city"] = o.City
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.ZipCode) {
		toSerialize["zip_code"] = o.ZipCode
	}
	if !IsNil(o.CountryName) {
		toSerialize["country_name"] = o.CountryName
	}
	if !IsNil(o.CountryCode) {
		toSerialize["country_code"] = o.CountryCode
	}
	if !IsNil(o.EmailAddress) {
		toSerialize["email_address"] = o.EmailAddress
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !IsNil(o.Fax) {
		toSerialize["fax"] = o.Fax
	}
	if !IsNil(o.MailingAddress) {
		toSerialize["mailing_address"] = o.MailingAddress
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PersonalInformation) UnmarshalJSON(data []byte) (err error) {
	varPersonalInformation := _PersonalInformation{}

	err = json.Unmarshal(data, &varPersonalInformation)

	if err != nil {
		return err
	}

	*o = PersonalInformation(varPersonalInformation)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "id_type")
		delete(additionalProperties, "handle")
		delete(additionalProperties, "name")
		delete(additionalProperties, "company")
		delete(additionalProperties, "street")
		delete(additionalProperties, "city")
		delete(additionalProperties, "state")
		delete(additionalProperties, "zip_code")
		delete(additionalProperties, "country_name")
		delete(additionalProperties, "country_code")
		delete(additionalProperties, "email_address")
		delete(additionalProperties, "phone")
		delete(additionalProperties, "fax")
		delete(additionalProperties, "mailing_address")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePersonalInformation struct {
	value *PersonalInformation
	isSet bool
}

func (v NullablePersonalInformation) Get() *PersonalInformation {
	return v.value
}

func (v *NullablePersonalInformation) Set(val *PersonalInformation) {
	v.value = val
	v.isSet = true
}

func (v NullablePersonalInformation) IsSet() bool {
	return v.isSet
}

func (v *NullablePersonalInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePersonalInformation(val *PersonalInformation) *NullablePersonalInformation {
	return &NullablePersonalInformation{value: val, isSet: true}
}

func (v NullablePersonalInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePersonalInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


