/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"encoding/json"
)

// checks if the DomainReputationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainReputationResponse{}

// DomainReputationResponse struct for DomainReputationResponse
type DomainReputationResponse struct {
	Input *DomainReputationInput `json:"input,omitempty"`
	AssessedAt *string `json:"assessed_at,omitempty"`
	Version *string `json:"version,omitempty"`
	ProcessingTimeMs *int32 `json:"processing_time_ms,omitempty"`
	RiskCategory *RiskCategory `json:"risk_category,omitempty"`
	DgaScore *DgaScore `json:"dga_score,omitempty"`
	TrustSignals *TrustSignals `json:"trust_signals,omitempty"`
	Intelligence *ReputationIntelligence `json:"intelligence,omitempty"`
	EvidenceSummary *EvidenceSummary `json:"evidence_summary,omitempty"`
	Errors []string `json:"errors,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DomainReputationResponse DomainReputationResponse

// NewDomainReputationResponse instantiates a new DomainReputationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainReputationResponse() *DomainReputationResponse {
	this := DomainReputationResponse{}
	return &this
}

// NewDomainReputationResponseWithDefaults instantiates a new DomainReputationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainReputationResponseWithDefaults() *DomainReputationResponse {
	this := DomainReputationResponse{}
	return &this
}

// GetInput returns the Input field value if set, zero value otherwise.
func (o *DomainReputationResponse) GetInput() DomainReputationInput {
	if o == nil || IsNil(o.Input) {
		var ret DomainReputationInput
		return ret
	}
	return *o.Input
}

// GetInputOk returns a tuple with the Input field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainReputationResponse) GetInputOk() (*DomainReputationInput, bool) {
	if o == nil || IsNil(o.Input) {
		return nil, false
	}
	return o.Input, true
}

// HasInput returns a boolean if a field has been set.
func (o *DomainReputationResponse) HasInput() bool {
	if o != nil && !IsNil(o.Input) {
		return true
	}

	return false
}

// SetInput gets a reference to the given DomainReputationInput and assigns it to the Input field.
func (o *DomainReputationResponse) SetInput(v DomainReputationInput) {
	o.Input = &v
}

// GetAssessedAt returns the AssessedAt field value if set, zero value otherwise.
func (o *DomainReputationResponse) GetAssessedAt() string {
	if o == nil || IsNil(o.AssessedAt) {
		var ret string
		return ret
	}
	return *o.AssessedAt
}

// GetAssessedAtOk returns a tuple with the AssessedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainReputationResponse) GetAssessedAtOk() (*string, bool) {
	if o == nil || IsNil(o.AssessedAt) {
		return nil, false
	}
	return o.AssessedAt, true
}

// HasAssessedAt returns a boolean if a field has been set.
func (o *DomainReputationResponse) HasAssessedAt() bool {
	if o != nil && !IsNil(o.AssessedAt) {
		return true
	}

	return false
}

// SetAssessedAt gets a reference to the given string and assigns it to the AssessedAt field.
func (o *DomainReputationResponse) SetAssessedAt(v string) {
	o.AssessedAt = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *DomainReputationResponse) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainReputationResponse) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *DomainReputationResponse) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *DomainReputationResponse) SetVersion(v string) {
	o.Version = &v
}

// GetProcessingTimeMs returns the ProcessingTimeMs field value if set, zero value otherwise.
func (o *DomainReputationResponse) GetProcessingTimeMs() int32 {
	if o == nil || IsNil(o.ProcessingTimeMs) {
		var ret int32
		return ret
	}
	return *o.ProcessingTimeMs
}

// GetProcessingTimeMsOk returns a tuple with the ProcessingTimeMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainReputationResponse) GetProcessingTimeMsOk() (*int32, bool) {
	if o == nil || IsNil(o.ProcessingTimeMs) {
		return nil, false
	}
	return o.ProcessingTimeMs, true
}

// HasProcessingTimeMs returns a boolean if a field has been set.
func (o *DomainReputationResponse) HasProcessingTimeMs() bool {
	if o != nil && !IsNil(o.ProcessingTimeMs) {
		return true
	}

	return false
}

// SetProcessingTimeMs gets a reference to the given int32 and assigns it to the ProcessingTimeMs field.
func (o *DomainReputationResponse) SetProcessingTimeMs(v int32) {
	o.ProcessingTimeMs = &v
}

// GetRiskCategory returns the RiskCategory field value if set, zero value otherwise.
func (o *DomainReputationResponse) GetRiskCategory() RiskCategory {
	if o == nil || IsNil(o.RiskCategory) {
		var ret RiskCategory
		return ret
	}
	return *o.RiskCategory
}

// GetRiskCategoryOk returns a tuple with the RiskCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainReputationResponse) GetRiskCategoryOk() (*RiskCategory, bool) {
	if o == nil || IsNil(o.RiskCategory) {
		return nil, false
	}
	return o.RiskCategory, true
}

// HasRiskCategory returns a boolean if a field has been set.
func (o *DomainReputationResponse) HasRiskCategory() bool {
	if o != nil && !IsNil(o.RiskCategory) {
		return true
	}

	return false
}

// SetRiskCategory gets a reference to the given RiskCategory and assigns it to the RiskCategory field.
func (o *DomainReputationResponse) SetRiskCategory(v RiskCategory) {
	o.RiskCategory = &v
}

// GetDgaScore returns the DgaScore field value if set, zero value otherwise.
func (o *DomainReputationResponse) GetDgaScore() DgaScore {
	if o == nil || IsNil(o.DgaScore) {
		var ret DgaScore
		return ret
	}
	return *o.DgaScore
}

// GetDgaScoreOk returns a tuple with the DgaScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainReputationResponse) GetDgaScoreOk() (*DgaScore, bool) {
	if o == nil || IsNil(o.DgaScore) {
		return nil, false
	}
	return o.DgaScore, true
}

// HasDgaScore returns a boolean if a field has been set.
func (o *DomainReputationResponse) HasDgaScore() bool {
	if o != nil && !IsNil(o.DgaScore) {
		return true
	}

	return false
}

// SetDgaScore gets a reference to the given DgaScore and assigns it to the DgaScore field.
func (o *DomainReputationResponse) SetDgaScore(v DgaScore) {
	o.DgaScore = &v
}

// GetTrustSignals returns the TrustSignals field value if set, zero value otherwise.
func (o *DomainReputationResponse) GetTrustSignals() TrustSignals {
	if o == nil || IsNil(o.TrustSignals) {
		var ret TrustSignals
		return ret
	}
	return *o.TrustSignals
}

// GetTrustSignalsOk returns a tuple with the TrustSignals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainReputationResponse) GetTrustSignalsOk() (*TrustSignals, bool) {
	if o == nil || IsNil(o.TrustSignals) {
		return nil, false
	}
	return o.TrustSignals, true
}

// HasTrustSignals returns a boolean if a field has been set.
func (o *DomainReputationResponse) HasTrustSignals() bool {
	if o != nil && !IsNil(o.TrustSignals) {
		return true
	}

	return false
}

// SetTrustSignals gets a reference to the given TrustSignals and assigns it to the TrustSignals field.
func (o *DomainReputationResponse) SetTrustSignals(v TrustSignals) {
	o.TrustSignals = &v
}

// GetIntelligence returns the Intelligence field value if set, zero value otherwise.
func (o *DomainReputationResponse) GetIntelligence() ReputationIntelligence {
	if o == nil || IsNil(o.Intelligence) {
		var ret ReputationIntelligence
		return ret
	}
	return *o.Intelligence
}

// GetIntelligenceOk returns a tuple with the Intelligence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainReputationResponse) GetIntelligenceOk() (*ReputationIntelligence, bool) {
	if o == nil || IsNil(o.Intelligence) {
		return nil, false
	}
	return o.Intelligence, true
}

// HasIntelligence returns a boolean if a field has been set.
func (o *DomainReputationResponse) HasIntelligence() bool {
	if o != nil && !IsNil(o.Intelligence) {
		return true
	}

	return false
}

// SetIntelligence gets a reference to the given ReputationIntelligence and assigns it to the Intelligence field.
func (o *DomainReputationResponse) SetIntelligence(v ReputationIntelligence) {
	o.Intelligence = &v
}

// GetEvidenceSummary returns the EvidenceSummary field value if set, zero value otherwise.
func (o *DomainReputationResponse) GetEvidenceSummary() EvidenceSummary {
	if o == nil || IsNil(o.EvidenceSummary) {
		var ret EvidenceSummary
		return ret
	}
	return *o.EvidenceSummary
}

// GetEvidenceSummaryOk returns a tuple with the EvidenceSummary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainReputationResponse) GetEvidenceSummaryOk() (*EvidenceSummary, bool) {
	if o == nil || IsNil(o.EvidenceSummary) {
		return nil, false
	}
	return o.EvidenceSummary, true
}

// HasEvidenceSummary returns a boolean if a field has been set.
func (o *DomainReputationResponse) HasEvidenceSummary() bool {
	if o != nil && !IsNil(o.EvidenceSummary) {
		return true
	}

	return false
}

// SetEvidenceSummary gets a reference to the given EvidenceSummary and assigns it to the EvidenceSummary field.
func (o *DomainReputationResponse) SetEvidenceSummary(v EvidenceSummary) {
	o.EvidenceSummary = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *DomainReputationResponse) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainReputationResponse) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *DomainReputationResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *DomainReputationResponse) SetErrors(v []string) {
	o.Errors = v
}

func (o DomainReputationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainReputationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Input) {
		toSerialize["input"] = o.Input
	}
	if !IsNil(o.AssessedAt) {
		toSerialize["assessed_at"] = o.AssessedAt
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.ProcessingTimeMs) {
		toSerialize["processing_time_ms"] = o.ProcessingTimeMs
	}
	if !IsNil(o.RiskCategory) {
		toSerialize["risk_category"] = o.RiskCategory
	}
	if !IsNil(o.DgaScore) {
		toSerialize["dga_score"] = o.DgaScore
	}
	if !IsNil(o.TrustSignals) {
		toSerialize["trust_signals"] = o.TrustSignals
	}
	if !IsNil(o.Intelligence) {
		toSerialize["intelligence"] = o.Intelligence
	}
	if !IsNil(o.EvidenceSummary) {
		toSerialize["evidence_summary"] = o.EvidenceSummary
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DomainReputationResponse) UnmarshalJSON(data []byte) (err error) {
	varDomainReputationResponse := _DomainReputationResponse{}

	err = json.Unmarshal(data, &varDomainReputationResponse)

	if err != nil {
		return err
	}

	*o = DomainReputationResponse(varDomainReputationResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "input")
		delete(additionalProperties, "assessed_at")
		delete(additionalProperties, "version")
		delete(additionalProperties, "processing_time_ms")
		delete(additionalProperties, "risk_category")
		delete(additionalProperties, "dga_score")
		delete(additionalProperties, "trust_signals")
		delete(additionalProperties, "intelligence")
		delete(additionalProperties, "evidence_summary")
		delete(additionalProperties, "errors")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDomainReputationResponse struct {
	value *DomainReputationResponse
	isSet bool
}

func (v NullableDomainReputationResponse) Get() *DomainReputationResponse {
	return v.value
}

func (v *NullableDomainReputationResponse) Set(val *DomainReputationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainReputationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainReputationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainReputationResponse(val *DomainReputationResponse) *NullableDomainReputationResponse {
	return &NullableDomainReputationResponse{value: val, isSet: true}
}

func (v NullableDomainReputationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainReputationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


