/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"encoding/json"
)

// checks if the DomainAvailabilityResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainAvailabilityResponse{}

// DomainAvailabilityResponse struct for DomainAvailabilityResponse
type DomainAvailabilityResponse struct {
	Domain *string `json:"domain,omitempty"`
	Availability *string `json:"availability,omitempty"`
	Message *string `json:"message,omitempty"`
	DomainAvailableResponse []DomainAvailabilityItem `json:"domain_available_response,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DomainAvailabilityResponse DomainAvailabilityResponse

// NewDomainAvailabilityResponse instantiates a new DomainAvailabilityResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainAvailabilityResponse() *DomainAvailabilityResponse {
	this := DomainAvailabilityResponse{}
	return &this
}

// NewDomainAvailabilityResponseWithDefaults instantiates a new DomainAvailabilityResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainAvailabilityResponseWithDefaults() *DomainAvailabilityResponse {
	this := DomainAvailabilityResponse{}
	return &this
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *DomainAvailabilityResponse) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainAvailabilityResponse) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *DomainAvailabilityResponse) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *DomainAvailabilityResponse) SetDomain(v string) {
	o.Domain = &v
}

// GetAvailability returns the Availability field value if set, zero value otherwise.
func (o *DomainAvailabilityResponse) GetAvailability() string {
	if o == nil || IsNil(o.Availability) {
		var ret string
		return ret
	}
	return *o.Availability
}

// GetAvailabilityOk returns a tuple with the Availability field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainAvailabilityResponse) GetAvailabilityOk() (*string, bool) {
	if o == nil || IsNil(o.Availability) {
		return nil, false
	}
	return o.Availability, true
}

// HasAvailability returns a boolean if a field has been set.
func (o *DomainAvailabilityResponse) HasAvailability() bool {
	if o != nil && !IsNil(o.Availability) {
		return true
	}

	return false
}

// SetAvailability gets a reference to the given string and assigns it to the Availability field.
func (o *DomainAvailabilityResponse) SetAvailability(v string) {
	o.Availability = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *DomainAvailabilityResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainAvailabilityResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *DomainAvailabilityResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *DomainAvailabilityResponse) SetMessage(v string) {
	o.Message = &v
}

// GetDomainAvailableResponse returns the DomainAvailableResponse field value if set, zero value otherwise.
func (o *DomainAvailabilityResponse) GetDomainAvailableResponse() []DomainAvailabilityItem {
	if o == nil || IsNil(o.DomainAvailableResponse) {
		var ret []DomainAvailabilityItem
		return ret
	}
	return o.DomainAvailableResponse
}

// GetDomainAvailableResponseOk returns a tuple with the DomainAvailableResponse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainAvailabilityResponse) GetDomainAvailableResponseOk() ([]DomainAvailabilityItem, bool) {
	if o == nil || IsNil(o.DomainAvailableResponse) {
		return nil, false
	}
	return o.DomainAvailableResponse, true
}

// HasDomainAvailableResponse returns a boolean if a field has been set.
func (o *DomainAvailabilityResponse) HasDomainAvailableResponse() bool {
	if o != nil && !IsNil(o.DomainAvailableResponse) {
		return true
	}

	return false
}

// SetDomainAvailableResponse gets a reference to the given []DomainAvailabilityItem and assigns it to the DomainAvailableResponse field.
func (o *DomainAvailabilityResponse) SetDomainAvailableResponse(v []DomainAvailabilityItem) {
	o.DomainAvailableResponse = v
}

func (o DomainAvailabilityResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainAvailabilityResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.Availability) {
		toSerialize["availability"] = o.Availability
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.DomainAvailableResponse) {
		toSerialize["domain_available_response"] = o.DomainAvailableResponse
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DomainAvailabilityResponse) UnmarshalJSON(data []byte) (err error) {
	varDomainAvailabilityResponse := _DomainAvailabilityResponse{}

	err = json.Unmarshal(data, &varDomainAvailabilityResponse)

	if err != nil {
		return err
	}

	*o = DomainAvailabilityResponse(varDomainAvailabilityResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "domain")
		delete(additionalProperties, "availability")
		delete(additionalProperties, "message")
		delete(additionalProperties, "domain_available_response")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDomainAvailabilityResponse struct {
	value *DomainAvailabilityResponse
	isSet bool
}

func (v NullableDomainAvailabilityResponse) Get() *DomainAvailabilityResponse {
	return v.value
}

func (v *NullableDomainAvailabilityResponse) Set(val *DomainAvailabilityResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainAvailabilityResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainAvailabilityResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainAvailabilityResponse(val *DomainAvailabilityResponse) *NullableDomainAvailabilityResponse {
	return &NullableDomainAvailabilityResponse{value: val, isSet: true}
}

func (v NullableDomainAvailabilityResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainAvailabilityResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


