/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"encoding/json"
)

// checks if the SslUnitInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SslUnitInfo{}

// SslUnitInfo struct for SslUnitInfo
type SslUnitInfo struct {
	CommonName *string `json:"commonName,omitempty"`
	Organization *string `json:"organization,omitempty"`
	OrganizationalUnit *string `json:"organizationalUnit,omitempty"`
	Locality *string `json:"locality,omitempty"`
	State *string `json:"state,omitempty"`
	Country *string `json:"country,omitempty"`
	IncCountry *string `json:"incCountry,omitempty"`
	IncState *string `json:"incState,omitempty"`
	BusinessCategory *string `json:"businessCategory,omitempty"`
	Street *string `json:"street,omitempty"`
	PostalCode *string `json:"postalCode,omitempty"`
	SerialNumber *string `json:"serialNumber,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SslUnitInfo SslUnitInfo

// NewSslUnitInfo instantiates a new SslUnitInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSslUnitInfo() *SslUnitInfo {
	this := SslUnitInfo{}
	return &this
}

// NewSslUnitInfoWithDefaults instantiates a new SslUnitInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSslUnitInfoWithDefaults() *SslUnitInfo {
	this := SslUnitInfo{}
	return &this
}

// GetCommonName returns the CommonName field value if set, zero value otherwise.
func (o *SslUnitInfo) GetCommonName() string {
	if o == nil || IsNil(o.CommonName) {
		var ret string
		return ret
	}
	return *o.CommonName
}

// GetCommonNameOk returns a tuple with the CommonName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SslUnitInfo) GetCommonNameOk() (*string, bool) {
	if o == nil || IsNil(o.CommonName) {
		return nil, false
	}
	return o.CommonName, true
}

// HasCommonName returns a boolean if a field has been set.
func (o *SslUnitInfo) HasCommonName() bool {
	if o != nil && !IsNil(o.CommonName) {
		return true
	}

	return false
}

// SetCommonName gets a reference to the given string and assigns it to the CommonName field.
func (o *SslUnitInfo) SetCommonName(v string) {
	o.CommonName = &v
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *SslUnitInfo) GetOrganization() string {
	if o == nil || IsNil(o.Organization) {
		var ret string
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SslUnitInfo) GetOrganizationOk() (*string, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *SslUnitInfo) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given string and assigns it to the Organization field.
func (o *SslUnitInfo) SetOrganization(v string) {
	o.Organization = &v
}

// GetOrganizationalUnit returns the OrganizationalUnit field value if set, zero value otherwise.
func (o *SslUnitInfo) GetOrganizationalUnit() string {
	if o == nil || IsNil(o.OrganizationalUnit) {
		var ret string
		return ret
	}
	return *o.OrganizationalUnit
}

// GetOrganizationalUnitOk returns a tuple with the OrganizationalUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SslUnitInfo) GetOrganizationalUnitOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationalUnit) {
		return nil, false
	}
	return o.OrganizationalUnit, true
}

// HasOrganizationalUnit returns a boolean if a field has been set.
func (o *SslUnitInfo) HasOrganizationalUnit() bool {
	if o != nil && !IsNil(o.OrganizationalUnit) {
		return true
	}

	return false
}

// SetOrganizationalUnit gets a reference to the given string and assigns it to the OrganizationalUnit field.
func (o *SslUnitInfo) SetOrganizationalUnit(v string) {
	o.OrganizationalUnit = &v
}

// GetLocality returns the Locality field value if set, zero value otherwise.
func (o *SslUnitInfo) GetLocality() string {
	if o == nil || IsNil(o.Locality) {
		var ret string
		return ret
	}
	return *o.Locality
}

// GetLocalityOk returns a tuple with the Locality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SslUnitInfo) GetLocalityOk() (*string, bool) {
	if o == nil || IsNil(o.Locality) {
		return nil, false
	}
	return o.Locality, true
}

// HasLocality returns a boolean if a field has been set.
func (o *SslUnitInfo) HasLocality() bool {
	if o != nil && !IsNil(o.Locality) {
		return true
	}

	return false
}

// SetLocality gets a reference to the given string and assigns it to the Locality field.
func (o *SslUnitInfo) SetLocality(v string) {
	o.Locality = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *SslUnitInfo) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SslUnitInfo) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *SslUnitInfo) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *SslUnitInfo) SetState(v string) {
	o.State = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *SslUnitInfo) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SslUnitInfo) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *SslUnitInfo) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *SslUnitInfo) SetCountry(v string) {
	o.Country = &v
}

// GetIncCountry returns the IncCountry field value if set, zero value otherwise.
func (o *SslUnitInfo) GetIncCountry() string {
	if o == nil || IsNil(o.IncCountry) {
		var ret string
		return ret
	}
	return *o.IncCountry
}

// GetIncCountryOk returns a tuple with the IncCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SslUnitInfo) GetIncCountryOk() (*string, bool) {
	if o == nil || IsNil(o.IncCountry) {
		return nil, false
	}
	return o.IncCountry, true
}

// HasIncCountry returns a boolean if a field has been set.
func (o *SslUnitInfo) HasIncCountry() bool {
	if o != nil && !IsNil(o.IncCountry) {
		return true
	}

	return false
}

// SetIncCountry gets a reference to the given string and assigns it to the IncCountry field.
func (o *SslUnitInfo) SetIncCountry(v string) {
	o.IncCountry = &v
}

// GetIncState returns the IncState field value if set, zero value otherwise.
func (o *SslUnitInfo) GetIncState() string {
	if o == nil || IsNil(o.IncState) {
		var ret string
		return ret
	}
	return *o.IncState
}

// GetIncStateOk returns a tuple with the IncState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SslUnitInfo) GetIncStateOk() (*string, bool) {
	if o == nil || IsNil(o.IncState) {
		return nil, false
	}
	return o.IncState, true
}

// HasIncState returns a boolean if a field has been set.
func (o *SslUnitInfo) HasIncState() bool {
	if o != nil && !IsNil(o.IncState) {
		return true
	}

	return false
}

// SetIncState gets a reference to the given string and assigns it to the IncState field.
func (o *SslUnitInfo) SetIncState(v string) {
	o.IncState = &v
}

// GetBusinessCategory returns the BusinessCategory field value if set, zero value otherwise.
func (o *SslUnitInfo) GetBusinessCategory() string {
	if o == nil || IsNil(o.BusinessCategory) {
		var ret string
		return ret
	}
	return *o.BusinessCategory
}

// GetBusinessCategoryOk returns a tuple with the BusinessCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SslUnitInfo) GetBusinessCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.BusinessCategory) {
		return nil, false
	}
	return o.BusinessCategory, true
}

// HasBusinessCategory returns a boolean if a field has been set.
func (o *SslUnitInfo) HasBusinessCategory() bool {
	if o != nil && !IsNil(o.BusinessCategory) {
		return true
	}

	return false
}

// SetBusinessCategory gets a reference to the given string and assigns it to the BusinessCategory field.
func (o *SslUnitInfo) SetBusinessCategory(v string) {
	o.BusinessCategory = &v
}

// GetStreet returns the Street field value if set, zero value otherwise.
func (o *SslUnitInfo) GetStreet() string {
	if o == nil || IsNil(o.Street) {
		var ret string
		return ret
	}
	return *o.Street
}

// GetStreetOk returns a tuple with the Street field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SslUnitInfo) GetStreetOk() (*string, bool) {
	if o == nil || IsNil(o.Street) {
		return nil, false
	}
	return o.Street, true
}

// HasStreet returns a boolean if a field has been set.
func (o *SslUnitInfo) HasStreet() bool {
	if o != nil && !IsNil(o.Street) {
		return true
	}

	return false
}

// SetStreet gets a reference to the given string and assigns it to the Street field.
func (o *SslUnitInfo) SetStreet(v string) {
	o.Street = &v
}

// GetPostalCode returns the PostalCode field value if set, zero value otherwise.
func (o *SslUnitInfo) GetPostalCode() string {
	if o == nil || IsNil(o.PostalCode) {
		var ret string
		return ret
	}
	return *o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SslUnitInfo) GetPostalCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PostalCode) {
		return nil, false
	}
	return o.PostalCode, true
}

// HasPostalCode returns a boolean if a field has been set.
func (o *SslUnitInfo) HasPostalCode() bool {
	if o != nil && !IsNil(o.PostalCode) {
		return true
	}

	return false
}

// SetPostalCode gets a reference to the given string and assigns it to the PostalCode field.
func (o *SslUnitInfo) SetPostalCode(v string) {
	o.PostalCode = &v
}

// GetSerialNumber returns the SerialNumber field value if set, zero value otherwise.
func (o *SslUnitInfo) GetSerialNumber() string {
	if o == nil || IsNil(o.SerialNumber) {
		var ret string
		return ret
	}
	return *o.SerialNumber
}

// GetSerialNumberOk returns a tuple with the SerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SslUnitInfo) GetSerialNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SerialNumber) {
		return nil, false
	}
	return o.SerialNumber, true
}

// HasSerialNumber returns a boolean if a field has been set.
func (o *SslUnitInfo) HasSerialNumber() bool {
	if o != nil && !IsNil(o.SerialNumber) {
		return true
	}

	return false
}

// SetSerialNumber gets a reference to the given string and assigns it to the SerialNumber field.
func (o *SslUnitInfo) SetSerialNumber(v string) {
	o.SerialNumber = &v
}

func (o SslUnitInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SslUnitInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CommonName) {
		toSerialize["commonName"] = o.CommonName
	}
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	if !IsNil(o.OrganizationalUnit) {
		toSerialize["organizationalUnit"] = o.OrganizationalUnit
	}
	if !IsNil(o.Locality) {
		toSerialize["locality"] = o.Locality
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.IncCountry) {
		toSerialize["incCountry"] = o.IncCountry
	}
	if !IsNil(o.IncState) {
		toSerialize["incState"] = o.IncState
	}
	if !IsNil(o.BusinessCategory) {
		toSerialize["businessCategory"] = o.BusinessCategory
	}
	if !IsNil(o.Street) {
		toSerialize["street"] = o.Street
	}
	if !IsNil(o.PostalCode) {
		toSerialize["postalCode"] = o.PostalCode
	}
	if !IsNil(o.SerialNumber) {
		toSerialize["serialNumber"] = o.SerialNumber
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SslUnitInfo) UnmarshalJSON(data []byte) (err error) {
	varSslUnitInfo := _SslUnitInfo{}

	err = json.Unmarshal(data, &varSslUnitInfo)

	if err != nil {
		return err
	}

	*o = SslUnitInfo(varSslUnitInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "commonName")
		delete(additionalProperties, "organization")
		delete(additionalProperties, "organizationalUnit")
		delete(additionalProperties, "locality")
		delete(additionalProperties, "state")
		delete(additionalProperties, "country")
		delete(additionalProperties, "incCountry")
		delete(additionalProperties, "incState")
		delete(additionalProperties, "businessCategory")
		delete(additionalProperties, "street")
		delete(additionalProperties, "postalCode")
		delete(additionalProperties, "serialNumber")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSslUnitInfo struct {
	value *SslUnitInfo
	isSet bool
}

func (v NullableSslUnitInfo) Get() *SslUnitInfo {
	return v.value
}

func (v *NullableSslUnitInfo) Set(val *SslUnitInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableSslUnitInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableSslUnitInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSslUnitInfo(val *SslUnitInfo) *NullableSslUnitInfo {
	return &NullableSslUnitInfo{value: val, isSet: true}
}

func (v NullableSslUnitInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSslUnitInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


