/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"encoding/json"
)

// checks if the ApiSubscription type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiSubscription{}

// ApiSubscription struct for ApiSubscription
type ApiSubscription struct {
	RequestLimit *int32 `json:"requestLimit,omitempty"`
	ServedRequests *int32 `json:"servedRequests,omitempty"`
	SubscriptionStatus *string `json:"subscriptionStatus,omitempty"`
	SurchargeRequestLimit *int32 `json:"surchargeRequestLimit,omitempty"`
	ServedSurchargeRequests *int32 `json:"servedSurchargeRequests,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ApiSubscription ApiSubscription

// NewApiSubscription instantiates a new ApiSubscription object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiSubscription() *ApiSubscription {
	this := ApiSubscription{}
	return &this
}

// NewApiSubscriptionWithDefaults instantiates a new ApiSubscription object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiSubscriptionWithDefaults() *ApiSubscription {
	this := ApiSubscription{}
	return &this
}

// GetRequestLimit returns the RequestLimit field value if set, zero value otherwise.
func (o *ApiSubscription) GetRequestLimit() int32 {
	if o == nil || IsNil(o.RequestLimit) {
		var ret int32
		return ret
	}
	return *o.RequestLimit
}

// GetRequestLimitOk returns a tuple with the RequestLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSubscription) GetRequestLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.RequestLimit) {
		return nil, false
	}
	return o.RequestLimit, true
}

// HasRequestLimit returns a boolean if a field has been set.
func (o *ApiSubscription) HasRequestLimit() bool {
	if o != nil && !IsNil(o.RequestLimit) {
		return true
	}

	return false
}

// SetRequestLimit gets a reference to the given int32 and assigns it to the RequestLimit field.
func (o *ApiSubscription) SetRequestLimit(v int32) {
	o.RequestLimit = &v
}

// GetServedRequests returns the ServedRequests field value if set, zero value otherwise.
func (o *ApiSubscription) GetServedRequests() int32 {
	if o == nil || IsNil(o.ServedRequests) {
		var ret int32
		return ret
	}
	return *o.ServedRequests
}

// GetServedRequestsOk returns a tuple with the ServedRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSubscription) GetServedRequestsOk() (*int32, bool) {
	if o == nil || IsNil(o.ServedRequests) {
		return nil, false
	}
	return o.ServedRequests, true
}

// HasServedRequests returns a boolean if a field has been set.
func (o *ApiSubscription) HasServedRequests() bool {
	if o != nil && !IsNil(o.ServedRequests) {
		return true
	}

	return false
}

// SetServedRequests gets a reference to the given int32 and assigns it to the ServedRequests field.
func (o *ApiSubscription) SetServedRequests(v int32) {
	o.ServedRequests = &v
}

// GetSubscriptionStatus returns the SubscriptionStatus field value if set, zero value otherwise.
func (o *ApiSubscription) GetSubscriptionStatus() string {
	if o == nil || IsNil(o.SubscriptionStatus) {
		var ret string
		return ret
	}
	return *o.SubscriptionStatus
}

// GetSubscriptionStatusOk returns a tuple with the SubscriptionStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSubscription) GetSubscriptionStatusOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionStatus) {
		return nil, false
	}
	return o.SubscriptionStatus, true
}

// HasSubscriptionStatus returns a boolean if a field has been set.
func (o *ApiSubscription) HasSubscriptionStatus() bool {
	if o != nil && !IsNil(o.SubscriptionStatus) {
		return true
	}

	return false
}

// SetSubscriptionStatus gets a reference to the given string and assigns it to the SubscriptionStatus field.
func (o *ApiSubscription) SetSubscriptionStatus(v string) {
	o.SubscriptionStatus = &v
}

// GetSurchargeRequestLimit returns the SurchargeRequestLimit field value if set, zero value otherwise.
func (o *ApiSubscription) GetSurchargeRequestLimit() int32 {
	if o == nil || IsNil(o.SurchargeRequestLimit) {
		var ret int32
		return ret
	}
	return *o.SurchargeRequestLimit
}

// GetSurchargeRequestLimitOk returns a tuple with the SurchargeRequestLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSubscription) GetSurchargeRequestLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.SurchargeRequestLimit) {
		return nil, false
	}
	return o.SurchargeRequestLimit, true
}

// HasSurchargeRequestLimit returns a boolean if a field has been set.
func (o *ApiSubscription) HasSurchargeRequestLimit() bool {
	if o != nil && !IsNil(o.SurchargeRequestLimit) {
		return true
	}

	return false
}

// SetSurchargeRequestLimit gets a reference to the given int32 and assigns it to the SurchargeRequestLimit field.
func (o *ApiSubscription) SetSurchargeRequestLimit(v int32) {
	o.SurchargeRequestLimit = &v
}

// GetServedSurchargeRequests returns the ServedSurchargeRequests field value if set, zero value otherwise.
func (o *ApiSubscription) GetServedSurchargeRequests() int32 {
	if o == nil || IsNil(o.ServedSurchargeRequests) {
		var ret int32
		return ret
	}
	return *o.ServedSurchargeRequests
}

// GetServedSurchargeRequestsOk returns a tuple with the ServedSurchargeRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSubscription) GetServedSurchargeRequestsOk() (*int32, bool) {
	if o == nil || IsNil(o.ServedSurchargeRequests) {
		return nil, false
	}
	return o.ServedSurchargeRequests, true
}

// HasServedSurchargeRequests returns a boolean if a field has been set.
func (o *ApiSubscription) HasServedSurchargeRequests() bool {
	if o != nil && !IsNil(o.ServedSurchargeRequests) {
		return true
	}

	return false
}

// SetServedSurchargeRequests gets a reference to the given int32 and assigns it to the ServedSurchargeRequests field.
func (o *ApiSubscription) SetServedSurchargeRequests(v int32) {
	o.ServedSurchargeRequests = &v
}

func (o ApiSubscription) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiSubscription) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RequestLimit) {
		toSerialize["requestLimit"] = o.RequestLimit
	}
	if !IsNil(o.ServedRequests) {
		toSerialize["servedRequests"] = o.ServedRequests
	}
	if !IsNil(o.SubscriptionStatus) {
		toSerialize["subscriptionStatus"] = o.SubscriptionStatus
	}
	if !IsNil(o.SurchargeRequestLimit) {
		toSerialize["surchargeRequestLimit"] = o.SurchargeRequestLimit
	}
	if !IsNil(o.ServedSurchargeRequests) {
		toSerialize["servedSurchargeRequests"] = o.ServedSurchargeRequests
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiSubscription) UnmarshalJSON(data []byte) (err error) {
	varApiSubscription := _ApiSubscription{}

	err = json.Unmarshal(data, &varApiSubscription)

	if err != nil {
		return err
	}

	*o = ApiSubscription(varApiSubscription)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "requestLimit")
		delete(additionalProperties, "servedRequests")
		delete(additionalProperties, "subscriptionStatus")
		delete(additionalProperties, "surchargeRequestLimit")
		delete(additionalProperties, "servedSurchargeRequests")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiSubscription struct {
	value *ApiSubscription
	isSet bool
}

func (v NullableApiSubscription) Get() *ApiSubscription {
	return v.value
}

func (v *NullableApiSubscription) Set(val *ApiSubscription) {
	v.value = val
	v.isSet = true
}

func (v NullableApiSubscription) IsSet() bool {
	return v.isSet
}

func (v *NullableApiSubscription) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiSubscription(val *ApiSubscription) *NullableApiSubscription {
	return &NullableApiSubscription{value: val, isSet: true}
}

func (v NullableApiSubscription) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiSubscription) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


