/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"encoding/json"
)

// checks if the IpReputationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IpReputationResponse{}

// IpReputationResponse struct for IpReputationResponse
type IpReputationResponse struct {
	Ip *string `json:"ip,omitempty"`
	Location *IpLocation `json:"location,omitempty"`
	Network *IpSecurityNetwork `json:"network,omitempty"`
	Asn *IpSecurityAsn `json:"asn,omitempty"`
	Security *IpSecurity `json:"security,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IpReputationResponse IpReputationResponse

// NewIpReputationResponse instantiates a new IpReputationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpReputationResponse() *IpReputationResponse {
	this := IpReputationResponse{}
	return &this
}

// NewIpReputationResponseWithDefaults instantiates a new IpReputationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpReputationResponseWithDefaults() *IpReputationResponse {
	this := IpReputationResponse{}
	return &this
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *IpReputationResponse) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpReputationResponse) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *IpReputationResponse) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *IpReputationResponse) SetIp(v string) {
	o.Ip = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *IpReputationResponse) GetLocation() IpLocation {
	if o == nil || IsNil(o.Location) {
		var ret IpLocation
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpReputationResponse) GetLocationOk() (*IpLocation, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *IpReputationResponse) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given IpLocation and assigns it to the Location field.
func (o *IpReputationResponse) SetLocation(v IpLocation) {
	o.Location = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *IpReputationResponse) GetNetwork() IpSecurityNetwork {
	if o == nil || IsNil(o.Network) {
		var ret IpSecurityNetwork
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpReputationResponse) GetNetworkOk() (*IpSecurityNetwork, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *IpReputationResponse) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given IpSecurityNetwork and assigns it to the Network field.
func (o *IpReputationResponse) SetNetwork(v IpSecurityNetwork) {
	o.Network = &v
}

// GetAsn returns the Asn field value if set, zero value otherwise.
func (o *IpReputationResponse) GetAsn() IpSecurityAsn {
	if o == nil || IsNil(o.Asn) {
		var ret IpSecurityAsn
		return ret
	}
	return *o.Asn
}

// GetAsnOk returns a tuple with the Asn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpReputationResponse) GetAsnOk() (*IpSecurityAsn, bool) {
	if o == nil || IsNil(o.Asn) {
		return nil, false
	}
	return o.Asn, true
}

// HasAsn returns a boolean if a field has been set.
func (o *IpReputationResponse) HasAsn() bool {
	if o != nil && !IsNil(o.Asn) {
		return true
	}

	return false
}

// SetAsn gets a reference to the given IpSecurityAsn and assigns it to the Asn field.
func (o *IpReputationResponse) SetAsn(v IpSecurityAsn) {
	o.Asn = &v
}

// GetSecurity returns the Security field value if set, zero value otherwise.
func (o *IpReputationResponse) GetSecurity() IpSecurity {
	if o == nil || IsNil(o.Security) {
		var ret IpSecurity
		return ret
	}
	return *o.Security
}

// GetSecurityOk returns a tuple with the Security field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpReputationResponse) GetSecurityOk() (*IpSecurity, bool) {
	if o == nil || IsNil(o.Security) {
		return nil, false
	}
	return o.Security, true
}

// HasSecurity returns a boolean if a field has been set.
func (o *IpReputationResponse) HasSecurity() bool {
	if o != nil && !IsNil(o.Security) {
		return true
	}

	return false
}

// SetSecurity gets a reference to the given IpSecurity and assigns it to the Security field.
func (o *IpReputationResponse) SetSecurity(v IpSecurity) {
	o.Security = &v
}

func (o IpReputationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IpReputationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	if !IsNil(o.Asn) {
		toSerialize["asn"] = o.Asn
	}
	if !IsNil(o.Security) {
		toSerialize["security"] = o.Security
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IpReputationResponse) UnmarshalJSON(data []byte) (err error) {
	varIpReputationResponse := _IpReputationResponse{}

	err = json.Unmarshal(data, &varIpReputationResponse)

	if err != nil {
		return err
	}

	*o = IpReputationResponse(varIpReputationResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ip")
		delete(additionalProperties, "location")
		delete(additionalProperties, "network")
		delete(additionalProperties, "asn")
		delete(additionalProperties, "security")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIpReputationResponse struct {
	value *IpReputationResponse
	isSet bool
}

func (v NullableIpReputationResponse) Get() *IpReputationResponse {
	return v.value
}

func (v *NullableIpReputationResponse) Set(val *IpReputationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIpReputationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIpReputationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpReputationResponse(val *IpReputationResponse) *NullableIpReputationResponse {
	return &NullableIpReputationResponse{value: val, isSet: true}
}

func (v NullableIpReputationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpReputationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


