/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"encoding/json"
)

// checks if the EvidenceSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EvidenceSummary{}

// EvidenceSummary struct for EvidenceSummary
type EvidenceSummary struct {
	WhyFlagged []string `json:"why_flagged,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EvidenceSummary EvidenceSummary

// NewEvidenceSummary instantiates a new EvidenceSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEvidenceSummary() *EvidenceSummary {
	this := EvidenceSummary{}
	return &this
}

// NewEvidenceSummaryWithDefaults instantiates a new EvidenceSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEvidenceSummaryWithDefaults() *EvidenceSummary {
	this := EvidenceSummary{}
	return &this
}

// GetWhyFlagged returns the WhyFlagged field value if set, zero value otherwise.
func (o *EvidenceSummary) GetWhyFlagged() []string {
	if o == nil || IsNil(o.WhyFlagged) {
		var ret []string
		return ret
	}
	return o.WhyFlagged
}

// GetWhyFlaggedOk returns a tuple with the WhyFlagged field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EvidenceSummary) GetWhyFlaggedOk() ([]string, bool) {
	if o == nil || IsNil(o.WhyFlagged) {
		return nil, false
	}
	return o.WhyFlagged, true
}

// HasWhyFlagged returns a boolean if a field has been set.
func (o *EvidenceSummary) HasWhyFlagged() bool {
	if o != nil && !IsNil(o.WhyFlagged) {
		return true
	}

	return false
}

// SetWhyFlagged gets a reference to the given []string and assigns it to the WhyFlagged field.
func (o *EvidenceSummary) SetWhyFlagged(v []string) {
	o.WhyFlagged = v
}

func (o EvidenceSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EvidenceSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.WhyFlagged) {
		toSerialize["why_flagged"] = o.WhyFlagged
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EvidenceSummary) UnmarshalJSON(data []byte) (err error) {
	varEvidenceSummary := _EvidenceSummary{}

	err = json.Unmarshal(data, &varEvidenceSummary)

	if err != nil {
		return err
	}

	*o = EvidenceSummary(varEvidenceSummary)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "why_flagged")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEvidenceSummary struct {
	value *EvidenceSummary
	isSet bool
}

func (v NullableEvidenceSummary) Get() *EvidenceSummary {
	return v.value
}

func (v *NullableEvidenceSummary) Set(val *EvidenceSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableEvidenceSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableEvidenceSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEvidenceSummary(val *EvidenceSummary) *NullableEvidenceSummary {
	return &NullableEvidenceSummary{value: val, isSet: true}
}

func (v NullableEvidenceSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEvidenceSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


