/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"encoding/json"
)

// checks if the DgaScore type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DgaScore{}

// DgaScore struct for DgaScore
type DgaScore struct {
	Score *float32 `json:"score,omitempty"`
	IsDga *bool `json:"is_dga,omitempty"`
	Model *string `json:"model,omitempty"`
	Features *DgaFeatures `json:"features,omitempty"`
	Interpretation *string `json:"interpretation,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DgaScore DgaScore

// NewDgaScore instantiates a new DgaScore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDgaScore() *DgaScore {
	this := DgaScore{}
	return &this
}

// NewDgaScoreWithDefaults instantiates a new DgaScore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDgaScoreWithDefaults() *DgaScore {
	this := DgaScore{}
	return &this
}

// GetScore returns the Score field value if set, zero value otherwise.
func (o *DgaScore) GetScore() float32 {
	if o == nil || IsNil(o.Score) {
		var ret float32
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DgaScore) GetScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.Score) {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *DgaScore) HasScore() bool {
	if o != nil && !IsNil(o.Score) {
		return true
	}

	return false
}

// SetScore gets a reference to the given float32 and assigns it to the Score field.
func (o *DgaScore) SetScore(v float32) {
	o.Score = &v
}

// GetIsDga returns the IsDga field value if set, zero value otherwise.
func (o *DgaScore) GetIsDga() bool {
	if o == nil || IsNil(o.IsDga) {
		var ret bool
		return ret
	}
	return *o.IsDga
}

// GetIsDgaOk returns a tuple with the IsDga field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DgaScore) GetIsDgaOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDga) {
		return nil, false
	}
	return o.IsDga, true
}

// HasIsDga returns a boolean if a field has been set.
func (o *DgaScore) HasIsDga() bool {
	if o != nil && !IsNil(o.IsDga) {
		return true
	}

	return false
}

// SetIsDga gets a reference to the given bool and assigns it to the IsDga field.
func (o *DgaScore) SetIsDga(v bool) {
	o.IsDga = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *DgaScore) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DgaScore) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *DgaScore) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *DgaScore) SetModel(v string) {
	o.Model = &v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *DgaScore) GetFeatures() DgaFeatures {
	if o == nil || IsNil(o.Features) {
		var ret DgaFeatures
		return ret
	}
	return *o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DgaScore) GetFeaturesOk() (*DgaFeatures, bool) {
	if o == nil || IsNil(o.Features) {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *DgaScore) HasFeatures() bool {
	if o != nil && !IsNil(o.Features) {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given DgaFeatures and assigns it to the Features field.
func (o *DgaScore) SetFeatures(v DgaFeatures) {
	o.Features = &v
}

// GetInterpretation returns the Interpretation field value if set, zero value otherwise.
func (o *DgaScore) GetInterpretation() string {
	if o == nil || IsNil(o.Interpretation) {
		var ret string
		return ret
	}
	return *o.Interpretation
}

// GetInterpretationOk returns a tuple with the Interpretation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DgaScore) GetInterpretationOk() (*string, bool) {
	if o == nil || IsNil(o.Interpretation) {
		return nil, false
	}
	return o.Interpretation, true
}

// HasInterpretation returns a boolean if a field has been set.
func (o *DgaScore) HasInterpretation() bool {
	if o != nil && !IsNil(o.Interpretation) {
		return true
	}

	return false
}

// SetInterpretation gets a reference to the given string and assigns it to the Interpretation field.
func (o *DgaScore) SetInterpretation(v string) {
	o.Interpretation = &v
}

func (o DgaScore) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DgaScore) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Score) {
		toSerialize["score"] = o.Score
	}
	if !IsNil(o.IsDga) {
		toSerialize["is_dga"] = o.IsDga
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.Features) {
		toSerialize["features"] = o.Features
	}
	if !IsNil(o.Interpretation) {
		toSerialize["interpretation"] = o.Interpretation
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DgaScore) UnmarshalJSON(data []byte) (err error) {
	varDgaScore := _DgaScore{}

	err = json.Unmarshal(data, &varDgaScore)

	if err != nil {
		return err
	}

	*o = DgaScore(varDgaScore)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "score")
		delete(additionalProperties, "is_dga")
		delete(additionalProperties, "model")
		delete(additionalProperties, "features")
		delete(additionalProperties, "interpretation")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDgaScore struct {
	value *DgaScore
	isSet bool
}

func (v NullableDgaScore) Get() *DgaScore {
	return v.value
}

func (v *NullableDgaScore) Set(val *DgaScore) {
	v.value = val
	v.isSet = true
}

func (v NullableDgaScore) IsSet() bool {
	return v.isSet
}

func (v *NullableDgaScore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDgaScore(val *DgaScore) *NullableDgaScore {
	return &NullableDgaScore{value: val, isSet: true}
}

func (v NullableDgaScore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDgaScore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


