/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"encoding/json"
)

// checks if the WhoisHistoricalItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WhoisHistoricalItem{}

// WhoisHistoricalItem struct for WhoisHistoricalItem
type WhoisHistoricalItem struct {
	Num *int32 `json:"num,omitempty"`
	Status *bool `json:"status,omitempty"`
	DomainName *string `json:"domain_name,omitempty"`
	QueryTime *string `json:"query_time,omitempty"`
	CreateDate *string `json:"create_date,omitempty"`
	UpdateDate *string `json:"update_date,omitempty"`
	ExpiryDate *string `json:"expiry_date,omitempty"`
	DomainRegistrar *RegistrarInformation `json:"domain_registrar,omitempty"`
	ResellerContact *ResellerContact `json:"reseller_contact,omitempty"`
	RegistrantContact *PersonalInformation `json:"registrant_contact,omitempty"`
	AdministrativeContact *PersonalInformation `json:"administrative_contact,omitempty"`
	TechnicalContact *PersonalInformation `json:"technical_contact,omitempty"`
	BillingContact *PersonalInformation `json:"billing_contact,omitempty"`
	NameServers []string `json:"name_servers,omitempty"`
	DomainStatus []string `json:"domain_status,omitempty"`
	WhoisRawDomain *string `json:"whois_raw_domain,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WhoisHistoricalItem WhoisHistoricalItem

// NewWhoisHistoricalItem instantiates a new WhoisHistoricalItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhoisHistoricalItem() *WhoisHistoricalItem {
	this := WhoisHistoricalItem{}
	return &this
}

// NewWhoisHistoricalItemWithDefaults instantiates a new WhoisHistoricalItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhoisHistoricalItemWithDefaults() *WhoisHistoricalItem {
	this := WhoisHistoricalItem{}
	return &this
}

// GetNum returns the Num field value if set, zero value otherwise.
func (o *WhoisHistoricalItem) GetNum() int32 {
	if o == nil || IsNil(o.Num) {
		var ret int32
		return ret
	}
	return *o.Num
}

// GetNumOk returns a tuple with the Num field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoisHistoricalItem) GetNumOk() (*int32, bool) {
	if o == nil || IsNil(o.Num) {
		return nil, false
	}
	return o.Num, true
}

// HasNum returns a boolean if a field has been set.
func (o *WhoisHistoricalItem) HasNum() bool {
	if o != nil && !IsNil(o.Num) {
		return true
	}

	return false
}

// SetNum gets a reference to the given int32 and assigns it to the Num field.
func (o *WhoisHistoricalItem) SetNum(v int32) {
	o.Num = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *WhoisHistoricalItem) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoisHistoricalItem) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *WhoisHistoricalItem) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *WhoisHistoricalItem) SetStatus(v bool) {
	o.Status = &v
}

// GetDomainName returns the DomainName field value if set, zero value otherwise.
func (o *WhoisHistoricalItem) GetDomainName() string {
	if o == nil || IsNil(o.DomainName) {
		var ret string
		return ret
	}
	return *o.DomainName
}

// GetDomainNameOk returns a tuple with the DomainName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoisHistoricalItem) GetDomainNameOk() (*string, bool) {
	if o == nil || IsNil(o.DomainName) {
		return nil, false
	}
	return o.DomainName, true
}

// HasDomainName returns a boolean if a field has been set.
func (o *WhoisHistoricalItem) HasDomainName() bool {
	if o != nil && !IsNil(o.DomainName) {
		return true
	}

	return false
}

// SetDomainName gets a reference to the given string and assigns it to the DomainName field.
func (o *WhoisHistoricalItem) SetDomainName(v string) {
	o.DomainName = &v
}

// GetQueryTime returns the QueryTime field value if set, zero value otherwise.
func (o *WhoisHistoricalItem) GetQueryTime() string {
	if o == nil || IsNil(o.QueryTime) {
		var ret string
		return ret
	}
	return *o.QueryTime
}

// GetQueryTimeOk returns a tuple with the QueryTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoisHistoricalItem) GetQueryTimeOk() (*string, bool) {
	if o == nil || IsNil(o.QueryTime) {
		return nil, false
	}
	return o.QueryTime, true
}

// HasQueryTime returns a boolean if a field has been set.
func (o *WhoisHistoricalItem) HasQueryTime() bool {
	if o != nil && !IsNil(o.QueryTime) {
		return true
	}

	return false
}

// SetQueryTime gets a reference to the given string and assigns it to the QueryTime field.
func (o *WhoisHistoricalItem) SetQueryTime(v string) {
	o.QueryTime = &v
}

// GetCreateDate returns the CreateDate field value if set, zero value otherwise.
func (o *WhoisHistoricalItem) GetCreateDate() string {
	if o == nil || IsNil(o.CreateDate) {
		var ret string
		return ret
	}
	return *o.CreateDate
}

// GetCreateDateOk returns a tuple with the CreateDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoisHistoricalItem) GetCreateDateOk() (*string, bool) {
	if o == nil || IsNil(o.CreateDate) {
		return nil, false
	}
	return o.CreateDate, true
}

// HasCreateDate returns a boolean if a field has been set.
func (o *WhoisHistoricalItem) HasCreateDate() bool {
	if o != nil && !IsNil(o.CreateDate) {
		return true
	}

	return false
}

// SetCreateDate gets a reference to the given string and assigns it to the CreateDate field.
func (o *WhoisHistoricalItem) SetCreateDate(v string) {
	o.CreateDate = &v
}

// GetUpdateDate returns the UpdateDate field value if set, zero value otherwise.
func (o *WhoisHistoricalItem) GetUpdateDate() string {
	if o == nil || IsNil(o.UpdateDate) {
		var ret string
		return ret
	}
	return *o.UpdateDate
}

// GetUpdateDateOk returns a tuple with the UpdateDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoisHistoricalItem) GetUpdateDateOk() (*string, bool) {
	if o == nil || IsNil(o.UpdateDate) {
		return nil, false
	}
	return o.UpdateDate, true
}

// HasUpdateDate returns a boolean if a field has been set.
func (o *WhoisHistoricalItem) HasUpdateDate() bool {
	if o != nil && !IsNil(o.UpdateDate) {
		return true
	}

	return false
}

// SetUpdateDate gets a reference to the given string and assigns it to the UpdateDate field.
func (o *WhoisHistoricalItem) SetUpdateDate(v string) {
	o.UpdateDate = &v
}

// GetExpiryDate returns the ExpiryDate field value if set, zero value otherwise.
func (o *WhoisHistoricalItem) GetExpiryDate() string {
	if o == nil || IsNil(o.ExpiryDate) {
		var ret string
		return ret
	}
	return *o.ExpiryDate
}

// GetExpiryDateOk returns a tuple with the ExpiryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoisHistoricalItem) GetExpiryDateOk() (*string, bool) {
	if o == nil || IsNil(o.ExpiryDate) {
		return nil, false
	}
	return o.ExpiryDate, true
}

// HasExpiryDate returns a boolean if a field has been set.
func (o *WhoisHistoricalItem) HasExpiryDate() bool {
	if o != nil && !IsNil(o.ExpiryDate) {
		return true
	}

	return false
}

// SetExpiryDate gets a reference to the given string and assigns it to the ExpiryDate field.
func (o *WhoisHistoricalItem) SetExpiryDate(v string) {
	o.ExpiryDate = &v
}

// GetDomainRegistrar returns the DomainRegistrar field value if set, zero value otherwise.
func (o *WhoisHistoricalItem) GetDomainRegistrar() RegistrarInformation {
	if o == nil || IsNil(o.DomainRegistrar) {
		var ret RegistrarInformation
		return ret
	}
	return *o.DomainRegistrar
}

// GetDomainRegistrarOk returns a tuple with the DomainRegistrar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoisHistoricalItem) GetDomainRegistrarOk() (*RegistrarInformation, bool) {
	if o == nil || IsNil(o.DomainRegistrar) {
		return nil, false
	}
	return o.DomainRegistrar, true
}

// HasDomainRegistrar returns a boolean if a field has been set.
func (o *WhoisHistoricalItem) HasDomainRegistrar() bool {
	if o != nil && !IsNil(o.DomainRegistrar) {
		return true
	}

	return false
}

// SetDomainRegistrar gets a reference to the given RegistrarInformation and assigns it to the DomainRegistrar field.
func (o *WhoisHistoricalItem) SetDomainRegistrar(v RegistrarInformation) {
	o.DomainRegistrar = &v
}

// GetResellerContact returns the ResellerContact field value if set, zero value otherwise.
func (o *WhoisHistoricalItem) GetResellerContact() ResellerContact {
	if o == nil || IsNil(o.ResellerContact) {
		var ret ResellerContact
		return ret
	}
	return *o.ResellerContact
}

// GetResellerContactOk returns a tuple with the ResellerContact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoisHistoricalItem) GetResellerContactOk() (*ResellerContact, bool) {
	if o == nil || IsNil(o.ResellerContact) {
		return nil, false
	}
	return o.ResellerContact, true
}

// HasResellerContact returns a boolean if a field has been set.
func (o *WhoisHistoricalItem) HasResellerContact() bool {
	if o != nil && !IsNil(o.ResellerContact) {
		return true
	}

	return false
}

// SetResellerContact gets a reference to the given ResellerContact and assigns it to the ResellerContact field.
func (o *WhoisHistoricalItem) SetResellerContact(v ResellerContact) {
	o.ResellerContact = &v
}

// GetRegistrantContact returns the RegistrantContact field value if set, zero value otherwise.
func (o *WhoisHistoricalItem) GetRegistrantContact() PersonalInformation {
	if o == nil || IsNil(o.RegistrantContact) {
		var ret PersonalInformation
		return ret
	}
	return *o.RegistrantContact
}

// GetRegistrantContactOk returns a tuple with the RegistrantContact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoisHistoricalItem) GetRegistrantContactOk() (*PersonalInformation, bool) {
	if o == nil || IsNil(o.RegistrantContact) {
		return nil, false
	}
	return o.RegistrantContact, true
}

// HasRegistrantContact returns a boolean if a field has been set.
func (o *WhoisHistoricalItem) HasRegistrantContact() bool {
	if o != nil && !IsNil(o.RegistrantContact) {
		return true
	}

	return false
}

// SetRegistrantContact gets a reference to the given PersonalInformation and assigns it to the RegistrantContact field.
func (o *WhoisHistoricalItem) SetRegistrantContact(v PersonalInformation) {
	o.RegistrantContact = &v
}

// GetAdministrativeContact returns the AdministrativeContact field value if set, zero value otherwise.
func (o *WhoisHistoricalItem) GetAdministrativeContact() PersonalInformation {
	if o == nil || IsNil(o.AdministrativeContact) {
		var ret PersonalInformation
		return ret
	}
	return *o.AdministrativeContact
}

// GetAdministrativeContactOk returns a tuple with the AdministrativeContact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoisHistoricalItem) GetAdministrativeContactOk() (*PersonalInformation, bool) {
	if o == nil || IsNil(o.AdministrativeContact) {
		return nil, false
	}
	return o.AdministrativeContact, true
}

// HasAdministrativeContact returns a boolean if a field has been set.
func (o *WhoisHistoricalItem) HasAdministrativeContact() bool {
	if o != nil && !IsNil(o.AdministrativeContact) {
		return true
	}

	return false
}

// SetAdministrativeContact gets a reference to the given PersonalInformation and assigns it to the AdministrativeContact field.
func (o *WhoisHistoricalItem) SetAdministrativeContact(v PersonalInformation) {
	o.AdministrativeContact = &v
}

// GetTechnicalContact returns the TechnicalContact field value if set, zero value otherwise.
func (o *WhoisHistoricalItem) GetTechnicalContact() PersonalInformation {
	if o == nil || IsNil(o.TechnicalContact) {
		var ret PersonalInformation
		return ret
	}
	return *o.TechnicalContact
}

// GetTechnicalContactOk returns a tuple with the TechnicalContact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoisHistoricalItem) GetTechnicalContactOk() (*PersonalInformation, bool) {
	if o == nil || IsNil(o.TechnicalContact) {
		return nil, false
	}
	return o.TechnicalContact, true
}

// HasTechnicalContact returns a boolean if a field has been set.
func (o *WhoisHistoricalItem) HasTechnicalContact() bool {
	if o != nil && !IsNil(o.TechnicalContact) {
		return true
	}

	return false
}

// SetTechnicalContact gets a reference to the given PersonalInformation and assigns it to the TechnicalContact field.
func (o *WhoisHistoricalItem) SetTechnicalContact(v PersonalInformation) {
	o.TechnicalContact = &v
}

// GetBillingContact returns the BillingContact field value if set, zero value otherwise.
func (o *WhoisHistoricalItem) GetBillingContact() PersonalInformation {
	if o == nil || IsNil(o.BillingContact) {
		var ret PersonalInformation
		return ret
	}
	return *o.BillingContact
}

// GetBillingContactOk returns a tuple with the BillingContact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoisHistoricalItem) GetBillingContactOk() (*PersonalInformation, bool) {
	if o == nil || IsNil(o.BillingContact) {
		return nil, false
	}
	return o.BillingContact, true
}

// HasBillingContact returns a boolean if a field has been set.
func (o *WhoisHistoricalItem) HasBillingContact() bool {
	if o != nil && !IsNil(o.BillingContact) {
		return true
	}

	return false
}

// SetBillingContact gets a reference to the given PersonalInformation and assigns it to the BillingContact field.
func (o *WhoisHistoricalItem) SetBillingContact(v PersonalInformation) {
	o.BillingContact = &v
}

// GetNameServers returns the NameServers field value if set, zero value otherwise.
func (o *WhoisHistoricalItem) GetNameServers() []string {
	if o == nil || IsNil(o.NameServers) {
		var ret []string
		return ret
	}
	return o.NameServers
}

// GetNameServersOk returns a tuple with the NameServers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoisHistoricalItem) GetNameServersOk() ([]string, bool) {
	if o == nil || IsNil(o.NameServers) {
		return nil, false
	}
	return o.NameServers, true
}

// HasNameServers returns a boolean if a field has been set.
func (o *WhoisHistoricalItem) HasNameServers() bool {
	if o != nil && !IsNil(o.NameServers) {
		return true
	}

	return false
}

// SetNameServers gets a reference to the given []string and assigns it to the NameServers field.
func (o *WhoisHistoricalItem) SetNameServers(v []string) {
	o.NameServers = v
}

// GetDomainStatus returns the DomainStatus field value if set, zero value otherwise.
func (o *WhoisHistoricalItem) GetDomainStatus() []string {
	if o == nil || IsNil(o.DomainStatus) {
		var ret []string
		return ret
	}
	return o.DomainStatus
}

// GetDomainStatusOk returns a tuple with the DomainStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoisHistoricalItem) GetDomainStatusOk() ([]string, bool) {
	if o == nil || IsNil(o.DomainStatus) {
		return nil, false
	}
	return o.DomainStatus, true
}

// HasDomainStatus returns a boolean if a field has been set.
func (o *WhoisHistoricalItem) HasDomainStatus() bool {
	if o != nil && !IsNil(o.DomainStatus) {
		return true
	}

	return false
}

// SetDomainStatus gets a reference to the given []string and assigns it to the DomainStatus field.
func (o *WhoisHistoricalItem) SetDomainStatus(v []string) {
	o.DomainStatus = v
}

// GetWhoisRawDomain returns the WhoisRawDomain field value if set, zero value otherwise.
func (o *WhoisHistoricalItem) GetWhoisRawDomain() string {
	if o == nil || IsNil(o.WhoisRawDomain) {
		var ret string
		return ret
	}
	return *o.WhoisRawDomain
}

// GetWhoisRawDomainOk returns a tuple with the WhoisRawDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhoisHistoricalItem) GetWhoisRawDomainOk() (*string, bool) {
	if o == nil || IsNil(o.WhoisRawDomain) {
		return nil, false
	}
	return o.WhoisRawDomain, true
}

// HasWhoisRawDomain returns a boolean if a field has been set.
func (o *WhoisHistoricalItem) HasWhoisRawDomain() bool {
	if o != nil && !IsNil(o.WhoisRawDomain) {
		return true
	}

	return false
}

// SetWhoisRawDomain gets a reference to the given string and assigns it to the WhoisRawDomain field.
func (o *WhoisHistoricalItem) SetWhoisRawDomain(v string) {
	o.WhoisRawDomain = &v
}

func (o WhoisHistoricalItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WhoisHistoricalItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Num) {
		toSerialize["num"] = o.Num
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.DomainName) {
		toSerialize["domain_name"] = o.DomainName
	}
	if !IsNil(o.QueryTime) {
		toSerialize["query_time"] = o.QueryTime
	}
	if !IsNil(o.CreateDate) {
		toSerialize["create_date"] = o.CreateDate
	}
	if !IsNil(o.UpdateDate) {
		toSerialize["update_date"] = o.UpdateDate
	}
	if !IsNil(o.ExpiryDate) {
		toSerialize["expiry_date"] = o.ExpiryDate
	}
	if !IsNil(o.DomainRegistrar) {
		toSerialize["domain_registrar"] = o.DomainRegistrar
	}
	if !IsNil(o.ResellerContact) {
		toSerialize["reseller_contact"] = o.ResellerContact
	}
	if !IsNil(o.RegistrantContact) {
		toSerialize["registrant_contact"] = o.RegistrantContact
	}
	if !IsNil(o.AdministrativeContact) {
		toSerialize["administrative_contact"] = o.AdministrativeContact
	}
	if !IsNil(o.TechnicalContact) {
		toSerialize["technical_contact"] = o.TechnicalContact
	}
	if !IsNil(o.BillingContact) {
		toSerialize["billing_contact"] = o.BillingContact
	}
	if !IsNil(o.NameServers) {
		toSerialize["name_servers"] = o.NameServers
	}
	if !IsNil(o.DomainStatus) {
		toSerialize["domain_status"] = o.DomainStatus
	}
	if !IsNil(o.WhoisRawDomain) {
		toSerialize["whois_raw_domain"] = o.WhoisRawDomain
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WhoisHistoricalItem) UnmarshalJSON(data []byte) (err error) {
	varWhoisHistoricalItem := _WhoisHistoricalItem{}

	err = json.Unmarshal(data, &varWhoisHistoricalItem)

	if err != nil {
		return err
	}

	*o = WhoisHistoricalItem(varWhoisHistoricalItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "num")
		delete(additionalProperties, "status")
		delete(additionalProperties, "domain_name")
		delete(additionalProperties, "query_time")
		delete(additionalProperties, "create_date")
		delete(additionalProperties, "update_date")
		delete(additionalProperties, "expiry_date")
		delete(additionalProperties, "domain_registrar")
		delete(additionalProperties, "reseller_contact")
		delete(additionalProperties, "registrant_contact")
		delete(additionalProperties, "administrative_contact")
		delete(additionalProperties, "technical_contact")
		delete(additionalProperties, "billing_contact")
		delete(additionalProperties, "name_servers")
		delete(additionalProperties, "domain_status")
		delete(additionalProperties, "whois_raw_domain")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWhoisHistoricalItem struct {
	value *WhoisHistoricalItem
	isSet bool
}

func (v NullableWhoisHistoricalItem) Get() *WhoisHistoricalItem {
	return v.value
}

func (v *NullableWhoisHistoricalItem) Set(val *WhoisHistoricalItem) {
	v.value = val
	v.isSet = true
}

func (v NullableWhoisHistoricalItem) IsSet() bool {
	return v.isSet
}

func (v *NullableWhoisHistoricalItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhoisHistoricalItem(val *WhoisHistoricalItem) *NullableWhoisHistoricalItem {
	return &NullableWhoisHistoricalItem{value: val, isSet: true}
}

func (v NullableWhoisHistoricalItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhoisHistoricalItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


