/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"encoding/json"
)

// checks if the ResellerContact type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResellerContact{}

// ResellerContact struct for ResellerContact
type ResellerContact struct {
	Name *string `json:"name,omitempty"`
	EmailAddress *string `json:"email_address,omitempty"`
	Phone *string `json:"phone,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ResellerContact ResellerContact

// NewResellerContact instantiates a new ResellerContact object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResellerContact() *ResellerContact {
	this := ResellerContact{}
	return &this
}

// NewResellerContactWithDefaults instantiates a new ResellerContact object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResellerContactWithDefaults() *ResellerContact {
	this := ResellerContact{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ResellerContact) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResellerContact) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ResellerContact) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ResellerContact) SetName(v string) {
	o.Name = &v
}

// GetEmailAddress returns the EmailAddress field value if set, zero value otherwise.
func (o *ResellerContact) GetEmailAddress() string {
	if o == nil || IsNil(o.EmailAddress) {
		var ret string
		return ret
	}
	return *o.EmailAddress
}

// GetEmailAddressOk returns a tuple with the EmailAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResellerContact) GetEmailAddressOk() (*string, bool) {
	if o == nil || IsNil(o.EmailAddress) {
		return nil, false
	}
	return o.EmailAddress, true
}

// HasEmailAddress returns a boolean if a field has been set.
func (o *ResellerContact) HasEmailAddress() bool {
	if o != nil && !IsNil(o.EmailAddress) {
		return true
	}

	return false
}

// SetEmailAddress gets a reference to the given string and assigns it to the EmailAddress field.
func (o *ResellerContact) SetEmailAddress(v string) {
	o.EmailAddress = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *ResellerContact) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResellerContact) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *ResellerContact) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *ResellerContact) SetPhone(v string) {
	o.Phone = &v
}

func (o ResellerContact) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResellerContact) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.EmailAddress) {
		toSerialize["email_address"] = o.EmailAddress
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ResellerContact) UnmarshalJSON(data []byte) (err error) {
	varResellerContact := _ResellerContact{}

	err = json.Unmarshal(data, &varResellerContact)

	if err != nil {
		return err
	}

	*o = ResellerContact(varResellerContact)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "email_address")
		delete(additionalProperties, "phone")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResellerContact struct {
	value *ResellerContact
	isSet bool
}

func (v NullableResellerContact) Get() *ResellerContact {
	return v.value
}

func (v *NullableResellerContact) Set(val *ResellerContact) {
	v.value = val
	v.isSet = true
}

func (v NullableResellerContact) IsSet() bool {
	return v.isSet
}

func (v *NullableResellerContact) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResellerContact(val *ResellerContact) *NullableResellerContact {
	return &NullableResellerContact{value: val, isSet: true}
}

func (v NullableResellerContact) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResellerContact) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


