/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"encoding/json"
)

// checks if the IpWhoisResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IpWhoisResponse{}

// IpWhoisResponse struct for IpWhoisResponse
type IpWhoisResponse struct {
	Status *bool `json:"status,omitempty"`
	IpAddress *string `json:"ip_address,omitempty"`
	AsNumber *string `json:"as_number,omitempty"`
	QueryTime *string `json:"query_time,omitempty"`
	WhoisServer *string `json:"whois_server,omitempty"`
	WhoisRawResponse *string `json:"whois_raw_response,omitempty"`
	RWhoisRawResponse *string `json:"r_whois_raw_response,omitempty"`
	InetNums []InetNum `json:"inet_nums,omitempty"`
	Organization *WhoisOrganization `json:"organization,omitempty"`
	Irt *Irt `json:"irt,omitempty"`
	AdministrativeContacts []WhoisPerson `json:"administrative_contacts,omitempty"`
	TechnicalContacts []WhoisPerson `json:"technical_contacts,omitempty"`
	AbuseContacts []WhoisPerson `json:"abuse_contacts,omitempty"`
	Routes []Route `json:"routes,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IpWhoisResponse IpWhoisResponse

// NewIpWhoisResponse instantiates a new IpWhoisResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpWhoisResponse() *IpWhoisResponse {
	this := IpWhoisResponse{}
	return &this
}

// NewIpWhoisResponseWithDefaults instantiates a new IpWhoisResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpWhoisResponseWithDefaults() *IpWhoisResponse {
	this := IpWhoisResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *IpWhoisResponse) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpWhoisResponse) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *IpWhoisResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *IpWhoisResponse) SetStatus(v bool) {
	o.Status = &v
}

// GetIpAddress returns the IpAddress field value if set, zero value otherwise.
func (o *IpWhoisResponse) GetIpAddress() string {
	if o == nil || IsNil(o.IpAddress) {
		var ret string
		return ret
	}
	return *o.IpAddress
}

// GetIpAddressOk returns a tuple with the IpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpWhoisResponse) GetIpAddressOk() (*string, bool) {
	if o == nil || IsNil(o.IpAddress) {
		return nil, false
	}
	return o.IpAddress, true
}

// HasIpAddress returns a boolean if a field has been set.
func (o *IpWhoisResponse) HasIpAddress() bool {
	if o != nil && !IsNil(o.IpAddress) {
		return true
	}

	return false
}

// SetIpAddress gets a reference to the given string and assigns it to the IpAddress field.
func (o *IpWhoisResponse) SetIpAddress(v string) {
	o.IpAddress = &v
}

// GetAsNumber returns the AsNumber field value if set, zero value otherwise.
func (o *IpWhoisResponse) GetAsNumber() string {
	if o == nil || IsNil(o.AsNumber) {
		var ret string
		return ret
	}
	return *o.AsNumber
}

// GetAsNumberOk returns a tuple with the AsNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpWhoisResponse) GetAsNumberOk() (*string, bool) {
	if o == nil || IsNil(o.AsNumber) {
		return nil, false
	}
	return o.AsNumber, true
}

// HasAsNumber returns a boolean if a field has been set.
func (o *IpWhoisResponse) HasAsNumber() bool {
	if o != nil && !IsNil(o.AsNumber) {
		return true
	}

	return false
}

// SetAsNumber gets a reference to the given string and assigns it to the AsNumber field.
func (o *IpWhoisResponse) SetAsNumber(v string) {
	o.AsNumber = &v
}

// GetQueryTime returns the QueryTime field value if set, zero value otherwise.
func (o *IpWhoisResponse) GetQueryTime() string {
	if o == nil || IsNil(o.QueryTime) {
		var ret string
		return ret
	}
	return *o.QueryTime
}

// GetQueryTimeOk returns a tuple with the QueryTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpWhoisResponse) GetQueryTimeOk() (*string, bool) {
	if o == nil || IsNil(o.QueryTime) {
		return nil, false
	}
	return o.QueryTime, true
}

// HasQueryTime returns a boolean if a field has been set.
func (o *IpWhoisResponse) HasQueryTime() bool {
	if o != nil && !IsNil(o.QueryTime) {
		return true
	}

	return false
}

// SetQueryTime gets a reference to the given string and assigns it to the QueryTime field.
func (o *IpWhoisResponse) SetQueryTime(v string) {
	o.QueryTime = &v
}

// GetWhoisServer returns the WhoisServer field value if set, zero value otherwise.
func (o *IpWhoisResponse) GetWhoisServer() string {
	if o == nil || IsNil(o.WhoisServer) {
		var ret string
		return ret
	}
	return *o.WhoisServer
}

// GetWhoisServerOk returns a tuple with the WhoisServer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpWhoisResponse) GetWhoisServerOk() (*string, bool) {
	if o == nil || IsNil(o.WhoisServer) {
		return nil, false
	}
	return o.WhoisServer, true
}

// HasWhoisServer returns a boolean if a field has been set.
func (o *IpWhoisResponse) HasWhoisServer() bool {
	if o != nil && !IsNil(o.WhoisServer) {
		return true
	}

	return false
}

// SetWhoisServer gets a reference to the given string and assigns it to the WhoisServer field.
func (o *IpWhoisResponse) SetWhoisServer(v string) {
	o.WhoisServer = &v
}

// GetWhoisRawResponse returns the WhoisRawResponse field value if set, zero value otherwise.
func (o *IpWhoisResponse) GetWhoisRawResponse() string {
	if o == nil || IsNil(o.WhoisRawResponse) {
		var ret string
		return ret
	}
	return *o.WhoisRawResponse
}

// GetWhoisRawResponseOk returns a tuple with the WhoisRawResponse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpWhoisResponse) GetWhoisRawResponseOk() (*string, bool) {
	if o == nil || IsNil(o.WhoisRawResponse) {
		return nil, false
	}
	return o.WhoisRawResponse, true
}

// HasWhoisRawResponse returns a boolean if a field has been set.
func (o *IpWhoisResponse) HasWhoisRawResponse() bool {
	if o != nil && !IsNil(o.WhoisRawResponse) {
		return true
	}

	return false
}

// SetWhoisRawResponse gets a reference to the given string and assigns it to the WhoisRawResponse field.
func (o *IpWhoisResponse) SetWhoisRawResponse(v string) {
	o.WhoisRawResponse = &v
}

// GetRWhoisRawResponse returns the RWhoisRawResponse field value if set, zero value otherwise.
func (o *IpWhoisResponse) GetRWhoisRawResponse() string {
	if o == nil || IsNil(o.RWhoisRawResponse) {
		var ret string
		return ret
	}
	return *o.RWhoisRawResponse
}

// GetRWhoisRawResponseOk returns a tuple with the RWhoisRawResponse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpWhoisResponse) GetRWhoisRawResponseOk() (*string, bool) {
	if o == nil || IsNil(o.RWhoisRawResponse) {
		return nil, false
	}
	return o.RWhoisRawResponse, true
}

// HasRWhoisRawResponse returns a boolean if a field has been set.
func (o *IpWhoisResponse) HasRWhoisRawResponse() bool {
	if o != nil && !IsNil(o.RWhoisRawResponse) {
		return true
	}

	return false
}

// SetRWhoisRawResponse gets a reference to the given string and assigns it to the RWhoisRawResponse field.
func (o *IpWhoisResponse) SetRWhoisRawResponse(v string) {
	o.RWhoisRawResponse = &v
}

// GetInetNums returns the InetNums field value if set, zero value otherwise.
func (o *IpWhoisResponse) GetInetNums() []InetNum {
	if o == nil || IsNil(o.InetNums) {
		var ret []InetNum
		return ret
	}
	return o.InetNums
}

// GetInetNumsOk returns a tuple with the InetNums field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpWhoisResponse) GetInetNumsOk() ([]InetNum, bool) {
	if o == nil || IsNil(o.InetNums) {
		return nil, false
	}
	return o.InetNums, true
}

// HasInetNums returns a boolean if a field has been set.
func (o *IpWhoisResponse) HasInetNums() bool {
	if o != nil && !IsNil(o.InetNums) {
		return true
	}

	return false
}

// SetInetNums gets a reference to the given []InetNum and assigns it to the InetNums field.
func (o *IpWhoisResponse) SetInetNums(v []InetNum) {
	o.InetNums = v
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *IpWhoisResponse) GetOrganization() WhoisOrganization {
	if o == nil || IsNil(o.Organization) {
		var ret WhoisOrganization
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpWhoisResponse) GetOrganizationOk() (*WhoisOrganization, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *IpWhoisResponse) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given WhoisOrganization and assigns it to the Organization field.
func (o *IpWhoisResponse) SetOrganization(v WhoisOrganization) {
	o.Organization = &v
}

// GetIrt returns the Irt field value if set, zero value otherwise.
func (o *IpWhoisResponse) GetIrt() Irt {
	if o == nil || IsNil(o.Irt) {
		var ret Irt
		return ret
	}
	return *o.Irt
}

// GetIrtOk returns a tuple with the Irt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpWhoisResponse) GetIrtOk() (*Irt, bool) {
	if o == nil || IsNil(o.Irt) {
		return nil, false
	}
	return o.Irt, true
}

// HasIrt returns a boolean if a field has been set.
func (o *IpWhoisResponse) HasIrt() bool {
	if o != nil && !IsNil(o.Irt) {
		return true
	}

	return false
}

// SetIrt gets a reference to the given Irt and assigns it to the Irt field.
func (o *IpWhoisResponse) SetIrt(v Irt) {
	o.Irt = &v
}

// GetAdministrativeContacts returns the AdministrativeContacts field value if set, zero value otherwise.
func (o *IpWhoisResponse) GetAdministrativeContacts() []WhoisPerson {
	if o == nil || IsNil(o.AdministrativeContacts) {
		var ret []WhoisPerson
		return ret
	}
	return o.AdministrativeContacts
}

// GetAdministrativeContactsOk returns a tuple with the AdministrativeContacts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpWhoisResponse) GetAdministrativeContactsOk() ([]WhoisPerson, bool) {
	if o == nil || IsNil(o.AdministrativeContacts) {
		return nil, false
	}
	return o.AdministrativeContacts, true
}

// HasAdministrativeContacts returns a boolean if a field has been set.
func (o *IpWhoisResponse) HasAdministrativeContacts() bool {
	if o != nil && !IsNil(o.AdministrativeContacts) {
		return true
	}

	return false
}

// SetAdministrativeContacts gets a reference to the given []WhoisPerson and assigns it to the AdministrativeContacts field.
func (o *IpWhoisResponse) SetAdministrativeContacts(v []WhoisPerson) {
	o.AdministrativeContacts = v
}

// GetTechnicalContacts returns the TechnicalContacts field value if set, zero value otherwise.
func (o *IpWhoisResponse) GetTechnicalContacts() []WhoisPerson {
	if o == nil || IsNil(o.TechnicalContacts) {
		var ret []WhoisPerson
		return ret
	}
	return o.TechnicalContacts
}

// GetTechnicalContactsOk returns a tuple with the TechnicalContacts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpWhoisResponse) GetTechnicalContactsOk() ([]WhoisPerson, bool) {
	if o == nil || IsNil(o.TechnicalContacts) {
		return nil, false
	}
	return o.TechnicalContacts, true
}

// HasTechnicalContacts returns a boolean if a field has been set.
func (o *IpWhoisResponse) HasTechnicalContacts() bool {
	if o != nil && !IsNil(o.TechnicalContacts) {
		return true
	}

	return false
}

// SetTechnicalContacts gets a reference to the given []WhoisPerson and assigns it to the TechnicalContacts field.
func (o *IpWhoisResponse) SetTechnicalContacts(v []WhoisPerson) {
	o.TechnicalContacts = v
}

// GetAbuseContacts returns the AbuseContacts field value if set, zero value otherwise.
func (o *IpWhoisResponse) GetAbuseContacts() []WhoisPerson {
	if o == nil || IsNil(o.AbuseContacts) {
		var ret []WhoisPerson
		return ret
	}
	return o.AbuseContacts
}

// GetAbuseContactsOk returns a tuple with the AbuseContacts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpWhoisResponse) GetAbuseContactsOk() ([]WhoisPerson, bool) {
	if o == nil || IsNil(o.AbuseContacts) {
		return nil, false
	}
	return o.AbuseContacts, true
}

// HasAbuseContacts returns a boolean if a field has been set.
func (o *IpWhoisResponse) HasAbuseContacts() bool {
	if o != nil && !IsNil(o.AbuseContacts) {
		return true
	}

	return false
}

// SetAbuseContacts gets a reference to the given []WhoisPerson and assigns it to the AbuseContacts field.
func (o *IpWhoisResponse) SetAbuseContacts(v []WhoisPerson) {
	o.AbuseContacts = v
}

// GetRoutes returns the Routes field value if set, zero value otherwise.
func (o *IpWhoisResponse) GetRoutes() []Route {
	if o == nil || IsNil(o.Routes) {
		var ret []Route
		return ret
	}
	return o.Routes
}

// GetRoutesOk returns a tuple with the Routes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpWhoisResponse) GetRoutesOk() ([]Route, bool) {
	if o == nil || IsNil(o.Routes) {
		return nil, false
	}
	return o.Routes, true
}

// HasRoutes returns a boolean if a field has been set.
func (o *IpWhoisResponse) HasRoutes() bool {
	if o != nil && !IsNil(o.Routes) {
		return true
	}

	return false
}

// SetRoutes gets a reference to the given []Route and assigns it to the Routes field.
func (o *IpWhoisResponse) SetRoutes(v []Route) {
	o.Routes = v
}

func (o IpWhoisResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IpWhoisResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.IpAddress) {
		toSerialize["ip_address"] = o.IpAddress
	}
	if !IsNil(o.AsNumber) {
		toSerialize["as_number"] = o.AsNumber
	}
	if !IsNil(o.QueryTime) {
		toSerialize["query_time"] = o.QueryTime
	}
	if !IsNil(o.WhoisServer) {
		toSerialize["whois_server"] = o.WhoisServer
	}
	if !IsNil(o.WhoisRawResponse) {
		toSerialize["whois_raw_response"] = o.WhoisRawResponse
	}
	if !IsNil(o.RWhoisRawResponse) {
		toSerialize["r_whois_raw_response"] = o.RWhoisRawResponse
	}
	if !IsNil(o.InetNums) {
		toSerialize["inet_nums"] = o.InetNums
	}
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	if !IsNil(o.Irt) {
		toSerialize["irt"] = o.Irt
	}
	if !IsNil(o.AdministrativeContacts) {
		toSerialize["administrative_contacts"] = o.AdministrativeContacts
	}
	if !IsNil(o.TechnicalContacts) {
		toSerialize["technical_contacts"] = o.TechnicalContacts
	}
	if !IsNil(o.AbuseContacts) {
		toSerialize["abuse_contacts"] = o.AbuseContacts
	}
	if !IsNil(o.Routes) {
		toSerialize["routes"] = o.Routes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IpWhoisResponse) UnmarshalJSON(data []byte) (err error) {
	varIpWhoisResponse := _IpWhoisResponse{}

	err = json.Unmarshal(data, &varIpWhoisResponse)

	if err != nil {
		return err
	}

	*o = IpWhoisResponse(varIpWhoisResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "ip_address")
		delete(additionalProperties, "as_number")
		delete(additionalProperties, "query_time")
		delete(additionalProperties, "whois_server")
		delete(additionalProperties, "whois_raw_response")
		delete(additionalProperties, "r_whois_raw_response")
		delete(additionalProperties, "inet_nums")
		delete(additionalProperties, "organization")
		delete(additionalProperties, "irt")
		delete(additionalProperties, "administrative_contacts")
		delete(additionalProperties, "technical_contacts")
		delete(additionalProperties, "abuse_contacts")
		delete(additionalProperties, "routes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIpWhoisResponse struct {
	value *IpWhoisResponse
	isSet bool
}

func (v NullableIpWhoisResponse) Get() *IpWhoisResponse {
	return v.value
}

func (v *NullableIpWhoisResponse) Set(val *IpWhoisResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIpWhoisResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIpWhoisResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpWhoisResponse(val *IpWhoisResponse) *NullableIpWhoisResponse {
	return &NullableIpWhoisResponse{value: val, isSet: true}
}

func (v NullableIpWhoisResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpWhoisResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


