/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"encoding/json"
)

// checks if the RegistrarInformation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegistrarInformation{}

// RegistrarInformation Registrar details (used by domain_registrar, abuse_contact).
type RegistrarInformation struct {
	Id *string `json:"id,omitempty"`
	IdType *string `json:"id_type,omitempty"`
	IanaId *string `json:"iana_id,omitempty"`
	RegistryId *string `json:"registry_id,omitempty"`
	Handle *string `json:"handle,omitempty"`
	Status *string `json:"status,omitempty"`
	RegistrarName *string `json:"registrar_name,omitempty"`
	NormalizedName *string `json:"normalized_name,omitempty"`
	WhoisServer *string `json:"whois_server,omitempty"`
	RdapServer *string `json:"rdap_server,omitempty"`
	WebsiteUrl *string `json:"website_url,omitempty"`
	EmailAddress *string `json:"email_address,omitempty"`
	PhoneNumber *string `json:"phone_number,omitempty"`
	AuthoritativeRegistryName *string `json:"authoritative_registry_name,omitempty"`
	OrganizationNumber *string `json:"organization_number,omitempty"`
	IsSponsor *bool `json:"is_sponsor,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RegistrarInformation RegistrarInformation

// NewRegistrarInformation instantiates a new RegistrarInformation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistrarInformation() *RegistrarInformation {
	this := RegistrarInformation{}
	return &this
}

// NewRegistrarInformationWithDefaults instantiates a new RegistrarInformation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistrarInformationWithDefaults() *RegistrarInformation {
	this := RegistrarInformation{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RegistrarInformation) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrarInformation) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RegistrarInformation) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *RegistrarInformation) SetId(v string) {
	o.Id = &v
}

// GetIdType returns the IdType field value if set, zero value otherwise.
func (o *RegistrarInformation) GetIdType() string {
	if o == nil || IsNil(o.IdType) {
		var ret string
		return ret
	}
	return *o.IdType
}

// GetIdTypeOk returns a tuple with the IdType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrarInformation) GetIdTypeOk() (*string, bool) {
	if o == nil || IsNil(o.IdType) {
		return nil, false
	}
	return o.IdType, true
}

// HasIdType returns a boolean if a field has been set.
func (o *RegistrarInformation) HasIdType() bool {
	if o != nil && !IsNil(o.IdType) {
		return true
	}

	return false
}

// SetIdType gets a reference to the given string and assigns it to the IdType field.
func (o *RegistrarInformation) SetIdType(v string) {
	o.IdType = &v
}

// GetIanaId returns the IanaId field value if set, zero value otherwise.
func (o *RegistrarInformation) GetIanaId() string {
	if o == nil || IsNil(o.IanaId) {
		var ret string
		return ret
	}
	return *o.IanaId
}

// GetIanaIdOk returns a tuple with the IanaId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrarInformation) GetIanaIdOk() (*string, bool) {
	if o == nil || IsNil(o.IanaId) {
		return nil, false
	}
	return o.IanaId, true
}

// HasIanaId returns a boolean if a field has been set.
func (o *RegistrarInformation) HasIanaId() bool {
	if o != nil && !IsNil(o.IanaId) {
		return true
	}

	return false
}

// SetIanaId gets a reference to the given string and assigns it to the IanaId field.
func (o *RegistrarInformation) SetIanaId(v string) {
	o.IanaId = &v
}

// GetRegistryId returns the RegistryId field value if set, zero value otherwise.
func (o *RegistrarInformation) GetRegistryId() string {
	if o == nil || IsNil(o.RegistryId) {
		var ret string
		return ret
	}
	return *o.RegistryId
}

// GetRegistryIdOk returns a tuple with the RegistryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrarInformation) GetRegistryIdOk() (*string, bool) {
	if o == nil || IsNil(o.RegistryId) {
		return nil, false
	}
	return o.RegistryId, true
}

// HasRegistryId returns a boolean if a field has been set.
func (o *RegistrarInformation) HasRegistryId() bool {
	if o != nil && !IsNil(o.RegistryId) {
		return true
	}

	return false
}

// SetRegistryId gets a reference to the given string and assigns it to the RegistryId field.
func (o *RegistrarInformation) SetRegistryId(v string) {
	o.RegistryId = &v
}

// GetHandle returns the Handle field value if set, zero value otherwise.
func (o *RegistrarInformation) GetHandle() string {
	if o == nil || IsNil(o.Handle) {
		var ret string
		return ret
	}
	return *o.Handle
}

// GetHandleOk returns a tuple with the Handle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrarInformation) GetHandleOk() (*string, bool) {
	if o == nil || IsNil(o.Handle) {
		return nil, false
	}
	return o.Handle, true
}

// HasHandle returns a boolean if a field has been set.
func (o *RegistrarInformation) HasHandle() bool {
	if o != nil && !IsNil(o.Handle) {
		return true
	}

	return false
}

// SetHandle gets a reference to the given string and assigns it to the Handle field.
func (o *RegistrarInformation) SetHandle(v string) {
	o.Handle = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *RegistrarInformation) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrarInformation) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *RegistrarInformation) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *RegistrarInformation) SetStatus(v string) {
	o.Status = &v
}

// GetRegistrarName returns the RegistrarName field value if set, zero value otherwise.
func (o *RegistrarInformation) GetRegistrarName() string {
	if o == nil || IsNil(o.RegistrarName) {
		var ret string
		return ret
	}
	return *o.RegistrarName
}

// GetRegistrarNameOk returns a tuple with the RegistrarName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrarInformation) GetRegistrarNameOk() (*string, bool) {
	if o == nil || IsNil(o.RegistrarName) {
		return nil, false
	}
	return o.RegistrarName, true
}

// HasRegistrarName returns a boolean if a field has been set.
func (o *RegistrarInformation) HasRegistrarName() bool {
	if o != nil && !IsNil(o.RegistrarName) {
		return true
	}

	return false
}

// SetRegistrarName gets a reference to the given string and assigns it to the RegistrarName field.
func (o *RegistrarInformation) SetRegistrarName(v string) {
	o.RegistrarName = &v
}

// GetNormalizedName returns the NormalizedName field value if set, zero value otherwise.
func (o *RegistrarInformation) GetNormalizedName() string {
	if o == nil || IsNil(o.NormalizedName) {
		var ret string
		return ret
	}
	return *o.NormalizedName
}

// GetNormalizedNameOk returns a tuple with the NormalizedName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrarInformation) GetNormalizedNameOk() (*string, bool) {
	if o == nil || IsNil(o.NormalizedName) {
		return nil, false
	}
	return o.NormalizedName, true
}

// HasNormalizedName returns a boolean if a field has been set.
func (o *RegistrarInformation) HasNormalizedName() bool {
	if o != nil && !IsNil(o.NormalizedName) {
		return true
	}

	return false
}

// SetNormalizedName gets a reference to the given string and assigns it to the NormalizedName field.
func (o *RegistrarInformation) SetNormalizedName(v string) {
	o.NormalizedName = &v
}

// GetWhoisServer returns the WhoisServer field value if set, zero value otherwise.
func (o *RegistrarInformation) GetWhoisServer() string {
	if o == nil || IsNil(o.WhoisServer) {
		var ret string
		return ret
	}
	return *o.WhoisServer
}

// GetWhoisServerOk returns a tuple with the WhoisServer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrarInformation) GetWhoisServerOk() (*string, bool) {
	if o == nil || IsNil(o.WhoisServer) {
		return nil, false
	}
	return o.WhoisServer, true
}

// HasWhoisServer returns a boolean if a field has been set.
func (o *RegistrarInformation) HasWhoisServer() bool {
	if o != nil && !IsNil(o.WhoisServer) {
		return true
	}

	return false
}

// SetWhoisServer gets a reference to the given string and assigns it to the WhoisServer field.
func (o *RegistrarInformation) SetWhoisServer(v string) {
	o.WhoisServer = &v
}

// GetRdapServer returns the RdapServer field value if set, zero value otherwise.
func (o *RegistrarInformation) GetRdapServer() string {
	if o == nil || IsNil(o.RdapServer) {
		var ret string
		return ret
	}
	return *o.RdapServer
}

// GetRdapServerOk returns a tuple with the RdapServer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrarInformation) GetRdapServerOk() (*string, bool) {
	if o == nil || IsNil(o.RdapServer) {
		return nil, false
	}
	return o.RdapServer, true
}

// HasRdapServer returns a boolean if a field has been set.
func (o *RegistrarInformation) HasRdapServer() bool {
	if o != nil && !IsNil(o.RdapServer) {
		return true
	}

	return false
}

// SetRdapServer gets a reference to the given string and assigns it to the RdapServer field.
func (o *RegistrarInformation) SetRdapServer(v string) {
	o.RdapServer = &v
}

// GetWebsiteUrl returns the WebsiteUrl field value if set, zero value otherwise.
func (o *RegistrarInformation) GetWebsiteUrl() string {
	if o == nil || IsNil(o.WebsiteUrl) {
		var ret string
		return ret
	}
	return *o.WebsiteUrl
}

// GetWebsiteUrlOk returns a tuple with the WebsiteUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrarInformation) GetWebsiteUrlOk() (*string, bool) {
	if o == nil || IsNil(o.WebsiteUrl) {
		return nil, false
	}
	return o.WebsiteUrl, true
}

// HasWebsiteUrl returns a boolean if a field has been set.
func (o *RegistrarInformation) HasWebsiteUrl() bool {
	if o != nil && !IsNil(o.WebsiteUrl) {
		return true
	}

	return false
}

// SetWebsiteUrl gets a reference to the given string and assigns it to the WebsiteUrl field.
func (o *RegistrarInformation) SetWebsiteUrl(v string) {
	o.WebsiteUrl = &v
}

// GetEmailAddress returns the EmailAddress field value if set, zero value otherwise.
func (o *RegistrarInformation) GetEmailAddress() string {
	if o == nil || IsNil(o.EmailAddress) {
		var ret string
		return ret
	}
	return *o.EmailAddress
}

// GetEmailAddressOk returns a tuple with the EmailAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrarInformation) GetEmailAddressOk() (*string, bool) {
	if o == nil || IsNil(o.EmailAddress) {
		return nil, false
	}
	return o.EmailAddress, true
}

// HasEmailAddress returns a boolean if a field has been set.
func (o *RegistrarInformation) HasEmailAddress() bool {
	if o != nil && !IsNil(o.EmailAddress) {
		return true
	}

	return false
}

// SetEmailAddress gets a reference to the given string and assigns it to the EmailAddress field.
func (o *RegistrarInformation) SetEmailAddress(v string) {
	o.EmailAddress = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *RegistrarInformation) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber) {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrarInformation) GetPhoneNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneNumber) {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *RegistrarInformation) HasPhoneNumber() bool {
	if o != nil && !IsNil(o.PhoneNumber) {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *RegistrarInformation) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetAuthoritativeRegistryName returns the AuthoritativeRegistryName field value if set, zero value otherwise.
func (o *RegistrarInformation) GetAuthoritativeRegistryName() string {
	if o == nil || IsNil(o.AuthoritativeRegistryName) {
		var ret string
		return ret
	}
	return *o.AuthoritativeRegistryName
}

// GetAuthoritativeRegistryNameOk returns a tuple with the AuthoritativeRegistryName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrarInformation) GetAuthoritativeRegistryNameOk() (*string, bool) {
	if o == nil || IsNil(o.AuthoritativeRegistryName) {
		return nil, false
	}
	return o.AuthoritativeRegistryName, true
}

// HasAuthoritativeRegistryName returns a boolean if a field has been set.
func (o *RegistrarInformation) HasAuthoritativeRegistryName() bool {
	if o != nil && !IsNil(o.AuthoritativeRegistryName) {
		return true
	}

	return false
}

// SetAuthoritativeRegistryName gets a reference to the given string and assigns it to the AuthoritativeRegistryName field.
func (o *RegistrarInformation) SetAuthoritativeRegistryName(v string) {
	o.AuthoritativeRegistryName = &v
}

// GetOrganizationNumber returns the OrganizationNumber field value if set, zero value otherwise.
func (o *RegistrarInformation) GetOrganizationNumber() string {
	if o == nil || IsNil(o.OrganizationNumber) {
		var ret string
		return ret
	}
	return *o.OrganizationNumber
}

// GetOrganizationNumberOk returns a tuple with the OrganizationNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrarInformation) GetOrganizationNumberOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationNumber) {
		return nil, false
	}
	return o.OrganizationNumber, true
}

// HasOrganizationNumber returns a boolean if a field has been set.
func (o *RegistrarInformation) HasOrganizationNumber() bool {
	if o != nil && !IsNil(o.OrganizationNumber) {
		return true
	}

	return false
}

// SetOrganizationNumber gets a reference to the given string and assigns it to the OrganizationNumber field.
func (o *RegistrarInformation) SetOrganizationNumber(v string) {
	o.OrganizationNumber = &v
}

// GetIsSponsor returns the IsSponsor field value if set, zero value otherwise.
func (o *RegistrarInformation) GetIsSponsor() bool {
	if o == nil || IsNil(o.IsSponsor) {
		var ret bool
		return ret
	}
	return *o.IsSponsor
}

// GetIsSponsorOk returns a tuple with the IsSponsor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrarInformation) GetIsSponsorOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSponsor) {
		return nil, false
	}
	return o.IsSponsor, true
}

// HasIsSponsor returns a boolean if a field has been set.
func (o *RegistrarInformation) HasIsSponsor() bool {
	if o != nil && !IsNil(o.IsSponsor) {
		return true
	}

	return false
}

// SetIsSponsor gets a reference to the given bool and assigns it to the IsSponsor field.
func (o *RegistrarInformation) SetIsSponsor(v bool) {
	o.IsSponsor = &v
}

func (o RegistrarInformation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegistrarInformation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IdType) {
		toSerialize["id_type"] = o.IdType
	}
	if !IsNil(o.IanaId) {
		toSerialize["iana_id"] = o.IanaId
	}
	if !IsNil(o.RegistryId) {
		toSerialize["registry_id"] = o.RegistryId
	}
	if !IsNil(o.Handle) {
		toSerialize["handle"] = o.Handle
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.RegistrarName) {
		toSerialize["registrar_name"] = o.RegistrarName
	}
	if !IsNil(o.NormalizedName) {
		toSerialize["normalized_name"] = o.NormalizedName
	}
	if !IsNil(o.WhoisServer) {
		toSerialize["whois_server"] = o.WhoisServer
	}
	if !IsNil(o.RdapServer) {
		toSerialize["rdap_server"] = o.RdapServer
	}
	if !IsNil(o.WebsiteUrl) {
		toSerialize["website_url"] = o.WebsiteUrl
	}
	if !IsNil(o.EmailAddress) {
		toSerialize["email_address"] = o.EmailAddress
	}
	if !IsNil(o.PhoneNumber) {
		toSerialize["phone_number"] = o.PhoneNumber
	}
	if !IsNil(o.AuthoritativeRegistryName) {
		toSerialize["authoritative_registry_name"] = o.AuthoritativeRegistryName
	}
	if !IsNil(o.OrganizationNumber) {
		toSerialize["organization_number"] = o.OrganizationNumber
	}
	if !IsNil(o.IsSponsor) {
		toSerialize["is_sponsor"] = o.IsSponsor
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RegistrarInformation) UnmarshalJSON(data []byte) (err error) {
	varRegistrarInformation := _RegistrarInformation{}

	err = json.Unmarshal(data, &varRegistrarInformation)

	if err != nil {
		return err
	}

	*o = RegistrarInformation(varRegistrarInformation)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "id_type")
		delete(additionalProperties, "iana_id")
		delete(additionalProperties, "registry_id")
		delete(additionalProperties, "handle")
		delete(additionalProperties, "status")
		delete(additionalProperties, "registrar_name")
		delete(additionalProperties, "normalized_name")
		delete(additionalProperties, "whois_server")
		delete(additionalProperties, "rdap_server")
		delete(additionalProperties, "website_url")
		delete(additionalProperties, "email_address")
		delete(additionalProperties, "phone_number")
		delete(additionalProperties, "authoritative_registry_name")
		delete(additionalProperties, "organization_number")
		delete(additionalProperties, "is_sponsor")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRegistrarInformation struct {
	value *RegistrarInformation
	isSet bool
}

func (v NullableRegistrarInformation) Get() *RegistrarInformation {
	return v.value
}

func (v *NullableRegistrarInformation) Set(val *RegistrarInformation) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistrarInformation) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistrarInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistrarInformation(val *RegistrarInformation) *NullableRegistrarInformation {
	return &NullableRegistrarInformation{value: val, isSet: true}
}

func (v NullableRegistrarInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistrarInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


