/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"encoding/json"
)

// checks if the ReputationSignals type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReputationSignals{}

// ReputationSignals struct for ReputationSignals
type ReputationSignals struct {
	Positive []ReputationSignal `json:"positive,omitempty"`
	Negative []ReputationSignal `json:"negative,omitempty"`
	Neutral []ReputationSignal `json:"neutral,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ReputationSignals ReputationSignals

// NewReputationSignals instantiates a new ReputationSignals object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReputationSignals() *ReputationSignals {
	this := ReputationSignals{}
	return &this
}

// NewReputationSignalsWithDefaults instantiates a new ReputationSignals object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReputationSignalsWithDefaults() *ReputationSignals {
	this := ReputationSignals{}
	return &this
}

// GetPositive returns the Positive field value if set, zero value otherwise.
func (o *ReputationSignals) GetPositive() []ReputationSignal {
	if o == nil || IsNil(o.Positive) {
		var ret []ReputationSignal
		return ret
	}
	return o.Positive
}

// GetPositiveOk returns a tuple with the Positive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReputationSignals) GetPositiveOk() ([]ReputationSignal, bool) {
	if o == nil || IsNil(o.Positive) {
		return nil, false
	}
	return o.Positive, true
}

// HasPositive returns a boolean if a field has been set.
func (o *ReputationSignals) HasPositive() bool {
	if o != nil && !IsNil(o.Positive) {
		return true
	}

	return false
}

// SetPositive gets a reference to the given []ReputationSignal and assigns it to the Positive field.
func (o *ReputationSignals) SetPositive(v []ReputationSignal) {
	o.Positive = v
}

// GetNegative returns the Negative field value if set, zero value otherwise.
func (o *ReputationSignals) GetNegative() []ReputationSignal {
	if o == nil || IsNil(o.Negative) {
		var ret []ReputationSignal
		return ret
	}
	return o.Negative
}

// GetNegativeOk returns a tuple with the Negative field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReputationSignals) GetNegativeOk() ([]ReputationSignal, bool) {
	if o == nil || IsNil(o.Negative) {
		return nil, false
	}
	return o.Negative, true
}

// HasNegative returns a boolean if a field has been set.
func (o *ReputationSignals) HasNegative() bool {
	if o != nil && !IsNil(o.Negative) {
		return true
	}

	return false
}

// SetNegative gets a reference to the given []ReputationSignal and assigns it to the Negative field.
func (o *ReputationSignals) SetNegative(v []ReputationSignal) {
	o.Negative = v
}

// GetNeutral returns the Neutral field value if set, zero value otherwise.
func (o *ReputationSignals) GetNeutral() []ReputationSignal {
	if o == nil || IsNil(o.Neutral) {
		var ret []ReputationSignal
		return ret
	}
	return o.Neutral
}

// GetNeutralOk returns a tuple with the Neutral field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReputationSignals) GetNeutralOk() ([]ReputationSignal, bool) {
	if o == nil || IsNil(o.Neutral) {
		return nil, false
	}
	return o.Neutral, true
}

// HasNeutral returns a boolean if a field has been set.
func (o *ReputationSignals) HasNeutral() bool {
	if o != nil && !IsNil(o.Neutral) {
		return true
	}

	return false
}

// SetNeutral gets a reference to the given []ReputationSignal and assigns it to the Neutral field.
func (o *ReputationSignals) SetNeutral(v []ReputationSignal) {
	o.Neutral = v
}

func (o ReputationSignals) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReputationSignals) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Positive) {
		toSerialize["positive"] = o.Positive
	}
	if !IsNil(o.Negative) {
		toSerialize["negative"] = o.Negative
	}
	if !IsNil(o.Neutral) {
		toSerialize["neutral"] = o.Neutral
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReputationSignals) UnmarshalJSON(data []byte) (err error) {
	varReputationSignals := _ReputationSignals{}

	err = json.Unmarshal(data, &varReputationSignals)

	if err != nil {
		return err
	}

	*o = ReputationSignals(varReputationSignals)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "positive")
		delete(additionalProperties, "negative")
		delete(additionalProperties, "neutral")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReputationSignals struct {
	value *ReputationSignals
	isSet bool
}

func (v NullableReputationSignals) Get() *ReputationSignals {
	return v.value
}

func (v *NullableReputationSignals) Set(val *ReputationSignals) {
	v.value = val
	v.isSet = true
}

func (v NullableReputationSignals) IsSet() bool {
	return v.isSet
}

func (v *NullableReputationSignals) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReputationSignals(val *ReputationSignals) *NullableReputationSignals {
	return &NullableReputationSignals{value: val, isSet: true}
}

func (v NullableReputationSignals) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReputationSignals) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


