/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkWhoisRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkWhoisRequest{}

// BulkWhoisRequest struct for BulkWhoisRequest
type BulkWhoisRequest struct {
	DomainNames []string `json:"domainNames"`
}

type _BulkWhoisRequest BulkWhoisRequest

// NewBulkWhoisRequest instantiates a new BulkWhoisRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkWhoisRequest(domainNames []string) *BulkWhoisRequest {
	this := BulkWhoisRequest{}
	this.DomainNames = domainNames
	return &this
}

// NewBulkWhoisRequestWithDefaults instantiates a new BulkWhoisRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkWhoisRequestWithDefaults() *BulkWhoisRequest {
	this := BulkWhoisRequest{}
	return &this
}

// GetDomainNames returns the DomainNames field value
func (o *BulkWhoisRequest) GetDomainNames() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.DomainNames
}

// GetDomainNamesOk returns a tuple with the DomainNames field value
// and a boolean to check if the value has been set.
func (o *BulkWhoisRequest) GetDomainNamesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DomainNames, true
}

// SetDomainNames sets field value
func (o *BulkWhoisRequest) SetDomainNames(v []string) {
	o.DomainNames = v
}

func (o BulkWhoisRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkWhoisRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["domainNames"] = o.DomainNames
	return toSerialize, nil
}

func (o *BulkWhoisRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"domainNames",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkWhoisRequest := _BulkWhoisRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkWhoisRequest)

	if err != nil {
		return err
	}

	*o = BulkWhoisRequest(varBulkWhoisRequest)

	return err
}

type NullableBulkWhoisRequest struct {
	value *BulkWhoisRequest
	isSet bool
}

func (v NullableBulkWhoisRequest) Get() *BulkWhoisRequest {
	return v.value
}

func (v *NullableBulkWhoisRequest) Set(val *BulkWhoisRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkWhoisRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkWhoisRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkWhoisRequest(val *BulkWhoisRequest) *NullableBulkWhoisRequest {
	return &NullableBulkWhoisRequest{value: val, isSet: true}
}

func (v NullableBulkWhoisRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkWhoisRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


