/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkGeolocationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkGeolocationRequest{}

// BulkGeolocationRequest struct for BulkGeolocationRequest
type BulkGeolocationRequest struct {
	Ips []string `json:"ips"`
}

type _BulkGeolocationRequest BulkGeolocationRequest

// NewBulkGeolocationRequest instantiates a new BulkGeolocationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkGeolocationRequest(ips []string) *BulkGeolocationRequest {
	this := BulkGeolocationRequest{}
	this.Ips = ips
	return &this
}

// NewBulkGeolocationRequestWithDefaults instantiates a new BulkGeolocationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkGeolocationRequestWithDefaults() *BulkGeolocationRequest {
	this := BulkGeolocationRequest{}
	return &this
}

// GetIps returns the Ips field value
func (o *BulkGeolocationRequest) GetIps() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Ips
}

// GetIpsOk returns a tuple with the Ips field value
// and a boolean to check if the value has been set.
func (o *BulkGeolocationRequest) GetIpsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ips, true
}

// SetIps sets field value
func (o *BulkGeolocationRequest) SetIps(v []string) {
	o.Ips = v
}

func (o BulkGeolocationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkGeolocationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ips"] = o.Ips
	return toSerialize, nil
}

func (o *BulkGeolocationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ips",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkGeolocationRequest := _BulkGeolocationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkGeolocationRequest)

	if err != nil {
		return err
	}

	*o = BulkGeolocationRequest(varBulkGeolocationRequest)

	return err
}

type NullableBulkGeolocationRequest struct {
	value *BulkGeolocationRequest
	isSet bool
}

func (v NullableBulkGeolocationRequest) Get() *BulkGeolocationRequest {
	return v.value
}

func (v *NullableBulkGeolocationRequest) Set(val *BulkGeolocationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkGeolocationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkGeolocationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkGeolocationRequest(val *BulkGeolocationRequest) *NullableBulkGeolocationRequest {
	return &NullableBulkGeolocationRequest{value: val, isSet: true}
}

func (v NullableBulkGeolocationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkGeolocationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


