/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"encoding/json"
)

// checks if the ApiCredits type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCredits{}

// ApiCredits struct for ApiCredits
type ApiCredits struct {
	TotalCredits *int32 `json:"totalCredits,omitempty"`
	ServedRequest *int32 `json:"servedRequest,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ApiCredits ApiCredits

// NewApiCredits instantiates a new ApiCredits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCredits() *ApiCredits {
	this := ApiCredits{}
	return &this
}

// NewApiCreditsWithDefaults instantiates a new ApiCredits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCreditsWithDefaults() *ApiCredits {
	this := ApiCredits{}
	return &this
}

// GetTotalCredits returns the TotalCredits field value if set, zero value otherwise.
func (o *ApiCredits) GetTotalCredits() int32 {
	if o == nil || IsNil(o.TotalCredits) {
		var ret int32
		return ret
	}
	return *o.TotalCredits
}

// GetTotalCreditsOk returns a tuple with the TotalCredits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCredits) GetTotalCreditsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCredits) {
		return nil, false
	}
	return o.TotalCredits, true
}

// HasTotalCredits returns a boolean if a field has been set.
func (o *ApiCredits) HasTotalCredits() bool {
	if o != nil && !IsNil(o.TotalCredits) {
		return true
	}

	return false
}

// SetTotalCredits gets a reference to the given int32 and assigns it to the TotalCredits field.
func (o *ApiCredits) SetTotalCredits(v int32) {
	o.TotalCredits = &v
}

// GetServedRequest returns the ServedRequest field value if set, zero value otherwise.
func (o *ApiCredits) GetServedRequest() int32 {
	if o == nil || IsNil(o.ServedRequest) {
		var ret int32
		return ret
	}
	return *o.ServedRequest
}

// GetServedRequestOk returns a tuple with the ServedRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCredits) GetServedRequestOk() (*int32, bool) {
	if o == nil || IsNil(o.ServedRequest) {
		return nil, false
	}
	return o.ServedRequest, true
}

// HasServedRequest returns a boolean if a field has been set.
func (o *ApiCredits) HasServedRequest() bool {
	if o != nil && !IsNil(o.ServedRequest) {
		return true
	}

	return false
}

// SetServedRequest gets a reference to the given int32 and assigns it to the ServedRequest field.
func (o *ApiCredits) SetServedRequest(v int32) {
	o.ServedRequest = &v
}

func (o ApiCredits) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCredits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalCredits) {
		toSerialize["totalCredits"] = o.TotalCredits
	}
	if !IsNil(o.ServedRequest) {
		toSerialize["servedRequest"] = o.ServedRequest
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiCredits) UnmarshalJSON(data []byte) (err error) {
	varApiCredits := _ApiCredits{}

	err = json.Unmarshal(data, &varApiCredits)

	if err != nil {
		return err
	}

	*o = ApiCredits(varApiCredits)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "totalCredits")
		delete(additionalProperties, "servedRequest")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiCredits struct {
	value *ApiCredits
	isSet bool
}

func (v NullableApiCredits) Get() *ApiCredits {
	return v.value
}

func (v *NullableApiCredits) Set(val *ApiCredits) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCredits) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCredits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCredits(val *ApiCredits) *NullableApiCredits {
	return &NullableApiCredits{value: val, isSet: true}
}

func (v NullableApiCredits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCredits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


