/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"encoding/json"
)

// checks if the DatabaseFileStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DatabaseFileStatus{}

// DatabaseFileStatus struct for DatabaseFileStatus
type DatabaseFileStatus struct {
	Newly *NewlyStatus `json:"newly,omitempty"`
	Expired *DateRangeStatus `json:"expired,omitempty"`
	CleanedExpired *DateRangeStatus `json:"cleaned_expired,omitempty"`
	Dropped *DateRangeStatus `json:"dropped,omitempty"`
	DroppedWithBacklinks *DateRangeStatus `json:"dropped_with_backlinks,omitempty"`
	ThreatFeed *ThreatFeedStatus `json:"threat_feed,omitempty"`
	DatabaseUpdates *DatabaseUpdates `json:"database_updates,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DatabaseFileStatus DatabaseFileStatus

// NewDatabaseFileStatus instantiates a new DatabaseFileStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDatabaseFileStatus() *DatabaseFileStatus {
	this := DatabaseFileStatus{}
	return &this
}

// NewDatabaseFileStatusWithDefaults instantiates a new DatabaseFileStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDatabaseFileStatusWithDefaults() *DatabaseFileStatus {
	this := DatabaseFileStatus{}
	return &this
}

// GetNewly returns the Newly field value if set, zero value otherwise.
func (o *DatabaseFileStatus) GetNewly() NewlyStatus {
	if o == nil || IsNil(o.Newly) {
		var ret NewlyStatus
		return ret
	}
	return *o.Newly
}

// GetNewlyOk returns a tuple with the Newly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabaseFileStatus) GetNewlyOk() (*NewlyStatus, bool) {
	if o == nil || IsNil(o.Newly) {
		return nil, false
	}
	return o.Newly, true
}

// HasNewly returns a boolean if a field has been set.
func (o *DatabaseFileStatus) HasNewly() bool {
	if o != nil && !IsNil(o.Newly) {
		return true
	}

	return false
}

// SetNewly gets a reference to the given NewlyStatus and assigns it to the Newly field.
func (o *DatabaseFileStatus) SetNewly(v NewlyStatus) {
	o.Newly = &v
}

// GetExpired returns the Expired field value if set, zero value otherwise.
func (o *DatabaseFileStatus) GetExpired() DateRangeStatus {
	if o == nil || IsNil(o.Expired) {
		var ret DateRangeStatus
		return ret
	}
	return *o.Expired
}

// GetExpiredOk returns a tuple with the Expired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabaseFileStatus) GetExpiredOk() (*DateRangeStatus, bool) {
	if o == nil || IsNil(o.Expired) {
		return nil, false
	}
	return o.Expired, true
}

// HasExpired returns a boolean if a field has been set.
func (o *DatabaseFileStatus) HasExpired() bool {
	if o != nil && !IsNil(o.Expired) {
		return true
	}

	return false
}

// SetExpired gets a reference to the given DateRangeStatus and assigns it to the Expired field.
func (o *DatabaseFileStatus) SetExpired(v DateRangeStatus) {
	o.Expired = &v
}

// GetCleanedExpired returns the CleanedExpired field value if set, zero value otherwise.
func (o *DatabaseFileStatus) GetCleanedExpired() DateRangeStatus {
	if o == nil || IsNil(o.CleanedExpired) {
		var ret DateRangeStatus
		return ret
	}
	return *o.CleanedExpired
}

// GetCleanedExpiredOk returns a tuple with the CleanedExpired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabaseFileStatus) GetCleanedExpiredOk() (*DateRangeStatus, bool) {
	if o == nil || IsNil(o.CleanedExpired) {
		return nil, false
	}
	return o.CleanedExpired, true
}

// HasCleanedExpired returns a boolean if a field has been set.
func (o *DatabaseFileStatus) HasCleanedExpired() bool {
	if o != nil && !IsNil(o.CleanedExpired) {
		return true
	}

	return false
}

// SetCleanedExpired gets a reference to the given DateRangeStatus and assigns it to the CleanedExpired field.
func (o *DatabaseFileStatus) SetCleanedExpired(v DateRangeStatus) {
	o.CleanedExpired = &v
}

// GetDropped returns the Dropped field value if set, zero value otherwise.
func (o *DatabaseFileStatus) GetDropped() DateRangeStatus {
	if o == nil || IsNil(o.Dropped) {
		var ret DateRangeStatus
		return ret
	}
	return *o.Dropped
}

// GetDroppedOk returns a tuple with the Dropped field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabaseFileStatus) GetDroppedOk() (*DateRangeStatus, bool) {
	if o == nil || IsNil(o.Dropped) {
		return nil, false
	}
	return o.Dropped, true
}

// HasDropped returns a boolean if a field has been set.
func (o *DatabaseFileStatus) HasDropped() bool {
	if o != nil && !IsNil(o.Dropped) {
		return true
	}

	return false
}

// SetDropped gets a reference to the given DateRangeStatus and assigns it to the Dropped field.
func (o *DatabaseFileStatus) SetDropped(v DateRangeStatus) {
	o.Dropped = &v
}

// GetDroppedWithBacklinks returns the DroppedWithBacklinks field value if set, zero value otherwise.
func (o *DatabaseFileStatus) GetDroppedWithBacklinks() DateRangeStatus {
	if o == nil || IsNil(o.DroppedWithBacklinks) {
		var ret DateRangeStatus
		return ret
	}
	return *o.DroppedWithBacklinks
}

// GetDroppedWithBacklinksOk returns a tuple with the DroppedWithBacklinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabaseFileStatus) GetDroppedWithBacklinksOk() (*DateRangeStatus, bool) {
	if o == nil || IsNil(o.DroppedWithBacklinks) {
		return nil, false
	}
	return o.DroppedWithBacklinks, true
}

// HasDroppedWithBacklinks returns a boolean if a field has been set.
func (o *DatabaseFileStatus) HasDroppedWithBacklinks() bool {
	if o != nil && !IsNil(o.DroppedWithBacklinks) {
		return true
	}

	return false
}

// SetDroppedWithBacklinks gets a reference to the given DateRangeStatus and assigns it to the DroppedWithBacklinks field.
func (o *DatabaseFileStatus) SetDroppedWithBacklinks(v DateRangeStatus) {
	o.DroppedWithBacklinks = &v
}

// GetThreatFeed returns the ThreatFeed field value if set, zero value otherwise.
func (o *DatabaseFileStatus) GetThreatFeed() ThreatFeedStatus {
	if o == nil || IsNil(o.ThreatFeed) {
		var ret ThreatFeedStatus
		return ret
	}
	return *o.ThreatFeed
}

// GetThreatFeedOk returns a tuple with the ThreatFeed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabaseFileStatus) GetThreatFeedOk() (*ThreatFeedStatus, bool) {
	if o == nil || IsNil(o.ThreatFeed) {
		return nil, false
	}
	return o.ThreatFeed, true
}

// HasThreatFeed returns a boolean if a field has been set.
func (o *DatabaseFileStatus) HasThreatFeed() bool {
	if o != nil && !IsNil(o.ThreatFeed) {
		return true
	}

	return false
}

// SetThreatFeed gets a reference to the given ThreatFeedStatus and assigns it to the ThreatFeed field.
func (o *DatabaseFileStatus) SetThreatFeed(v ThreatFeedStatus) {
	o.ThreatFeed = &v
}

// GetDatabaseUpdates returns the DatabaseUpdates field value if set, zero value otherwise.
func (o *DatabaseFileStatus) GetDatabaseUpdates() DatabaseUpdates {
	if o == nil || IsNil(o.DatabaseUpdates) {
		var ret DatabaseUpdates
		return ret
	}
	return *o.DatabaseUpdates
}

// GetDatabaseUpdatesOk returns a tuple with the DatabaseUpdates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabaseFileStatus) GetDatabaseUpdatesOk() (*DatabaseUpdates, bool) {
	if o == nil || IsNil(o.DatabaseUpdates) {
		return nil, false
	}
	return o.DatabaseUpdates, true
}

// HasDatabaseUpdates returns a boolean if a field has been set.
func (o *DatabaseFileStatus) HasDatabaseUpdates() bool {
	if o != nil && !IsNil(o.DatabaseUpdates) {
		return true
	}

	return false
}

// SetDatabaseUpdates gets a reference to the given DatabaseUpdates and assigns it to the DatabaseUpdates field.
func (o *DatabaseFileStatus) SetDatabaseUpdates(v DatabaseUpdates) {
	o.DatabaseUpdates = &v
}

func (o DatabaseFileStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DatabaseFileStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Newly) {
		toSerialize["newly"] = o.Newly
	}
	if !IsNil(o.Expired) {
		toSerialize["expired"] = o.Expired
	}
	if !IsNil(o.CleanedExpired) {
		toSerialize["cleaned_expired"] = o.CleanedExpired
	}
	if !IsNil(o.Dropped) {
		toSerialize["dropped"] = o.Dropped
	}
	if !IsNil(o.DroppedWithBacklinks) {
		toSerialize["dropped_with_backlinks"] = o.DroppedWithBacklinks
	}
	if !IsNil(o.ThreatFeed) {
		toSerialize["threat_feed"] = o.ThreatFeed
	}
	if !IsNil(o.DatabaseUpdates) {
		toSerialize["database_updates"] = o.DatabaseUpdates
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DatabaseFileStatus) UnmarshalJSON(data []byte) (err error) {
	varDatabaseFileStatus := _DatabaseFileStatus{}

	err = json.Unmarshal(data, &varDatabaseFileStatus)

	if err != nil {
		return err
	}

	*o = DatabaseFileStatus(varDatabaseFileStatus)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "newly")
		delete(additionalProperties, "expired")
		delete(additionalProperties, "cleaned_expired")
		delete(additionalProperties, "dropped")
		delete(additionalProperties, "dropped_with_backlinks")
		delete(additionalProperties, "threat_feed")
		delete(additionalProperties, "database_updates")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDatabaseFileStatus struct {
	value *DatabaseFileStatus
	isSet bool
}

func (v NullableDatabaseFileStatus) Get() *DatabaseFileStatus {
	return v.value
}

func (v *NullableDatabaseFileStatus) Set(val *DatabaseFileStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableDatabaseFileStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableDatabaseFileStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDatabaseFileStatus(val *DatabaseFileStatus) *NullableDatabaseFileStatus {
	return &NullableDatabaseFileStatus{value: val, isSet: true}
}

func (v NullableDatabaseFileStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDatabaseFileStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


