/*
WhoisFreaks API

Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com 

API version: 1.0.0
Contact: support@whoisfreaks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whoisfreaks

import (
	"encoding/json"
)

// checks if the AccountUsageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountUsageResponse{}

// AccountUsageResponse struct for AccountUsageResponse
type AccountUsageResponse struct {
	ApiKey *string `json:"apiKey,omitempty"`
	ApiCredits *ApiCredits `json:"apiCredits,omitempty"`
	ApiSubscription *ApiSubscription `json:"apiSubscription,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AccountUsageResponse AccountUsageResponse

// NewAccountUsageResponse instantiates a new AccountUsageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountUsageResponse() *AccountUsageResponse {
	this := AccountUsageResponse{}
	return &this
}

// NewAccountUsageResponseWithDefaults instantiates a new AccountUsageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountUsageResponseWithDefaults() *AccountUsageResponse {
	this := AccountUsageResponse{}
	return &this
}

// GetApiKey returns the ApiKey field value if set, zero value otherwise.
func (o *AccountUsageResponse) GetApiKey() string {
	if o == nil || IsNil(o.ApiKey) {
		var ret string
		return ret
	}
	return *o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountUsageResponse) GetApiKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ApiKey) {
		return nil, false
	}
	return o.ApiKey, true
}

// HasApiKey returns a boolean if a field has been set.
func (o *AccountUsageResponse) HasApiKey() bool {
	if o != nil && !IsNil(o.ApiKey) {
		return true
	}

	return false
}

// SetApiKey gets a reference to the given string and assigns it to the ApiKey field.
func (o *AccountUsageResponse) SetApiKey(v string) {
	o.ApiKey = &v
}

// GetApiCredits returns the ApiCredits field value if set, zero value otherwise.
func (o *AccountUsageResponse) GetApiCredits() ApiCredits {
	if o == nil || IsNil(o.ApiCredits) {
		var ret ApiCredits
		return ret
	}
	return *o.ApiCredits
}

// GetApiCreditsOk returns a tuple with the ApiCredits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountUsageResponse) GetApiCreditsOk() (*ApiCredits, bool) {
	if o == nil || IsNil(o.ApiCredits) {
		return nil, false
	}
	return o.ApiCredits, true
}

// HasApiCredits returns a boolean if a field has been set.
func (o *AccountUsageResponse) HasApiCredits() bool {
	if o != nil && !IsNil(o.ApiCredits) {
		return true
	}

	return false
}

// SetApiCredits gets a reference to the given ApiCredits and assigns it to the ApiCredits field.
func (o *AccountUsageResponse) SetApiCredits(v ApiCredits) {
	o.ApiCredits = &v
}

// GetApiSubscription returns the ApiSubscription field value if set, zero value otherwise.
func (o *AccountUsageResponse) GetApiSubscription() ApiSubscription {
	if o == nil || IsNil(o.ApiSubscription) {
		var ret ApiSubscription
		return ret
	}
	return *o.ApiSubscription
}

// GetApiSubscriptionOk returns a tuple with the ApiSubscription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountUsageResponse) GetApiSubscriptionOk() (*ApiSubscription, bool) {
	if o == nil || IsNil(o.ApiSubscription) {
		return nil, false
	}
	return o.ApiSubscription, true
}

// HasApiSubscription returns a boolean if a field has been set.
func (o *AccountUsageResponse) HasApiSubscription() bool {
	if o != nil && !IsNil(o.ApiSubscription) {
		return true
	}

	return false
}

// SetApiSubscription gets a reference to the given ApiSubscription and assigns it to the ApiSubscription field.
func (o *AccountUsageResponse) SetApiSubscription(v ApiSubscription) {
	o.ApiSubscription = &v
}

func (o AccountUsageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountUsageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApiKey) {
		toSerialize["apiKey"] = o.ApiKey
	}
	if !IsNil(o.ApiCredits) {
		toSerialize["apiCredits"] = o.ApiCredits
	}
	if !IsNil(o.ApiSubscription) {
		toSerialize["apiSubscription"] = o.ApiSubscription
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AccountUsageResponse) UnmarshalJSON(data []byte) (err error) {
	varAccountUsageResponse := _AccountUsageResponse{}

	err = json.Unmarshal(data, &varAccountUsageResponse)

	if err != nil {
		return err
	}

	*o = AccountUsageResponse(varAccountUsageResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "apiKey")
		delete(additionalProperties, "apiCredits")
		delete(additionalProperties, "apiSubscription")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAccountUsageResponse struct {
	value *AccountUsageResponse
	isSet bool
}

func (v NullableAccountUsageResponse) Get() *AccountUsageResponse {
	return v.value
}

func (v *NullableAccountUsageResponse) Set(val *AccountUsageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountUsageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountUsageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountUsageResponse(val *AccountUsageResponse) *NullableAccountUsageResponse {
	return &NullableAccountUsageResponse{value: val, isSet: true}
}

func (v NullableAccountUsageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountUsageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


